### ISSUE TITLE
panic in 8.5.0

### ISSUE THREAD

**Issue by graphaelli** [elastic/elastic-agent#1330]
- Version: 8.5.0-SNAPSHOT (at ce8c49b15419b0180448ea2a4f525c150edc4a85)
- Steps to Reproduce:

```
git clone git@github.com:elastic/apm-integration-testing.git .
./scripts/compose.py start 8.5.0 --with-opbeans-go
```

wait for the elastic agent container to exit 2 with a panic.  logs are:

<details>
<summary>logs are:</summary>

```
Performing setup of Fleet in Kibana

Policy selected for enrollment:  fleet-server-apm-policy
{"log.level":"info","@timestamp":"2022-09-28T00:42:22.014Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":587},"message":"Spawning Elastic Agent daemon as a subprocess to complete bootstrap process.","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-09-28T00:42:22.195Z","log.origin":{"file.name":"cmd/run.go","file.line":202},"message":"APM instrumentation disabled","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-09-28T00:42:22.196Z","log.origin":{"file.name":"application/application.go","file.line":78},"message":"Detecting execution mode","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-09-28T00:42:22.215Z","log.origin":{"file.name":"application/application.go","file.line":98},"message":"Agent is in Fleet Server bootstrap mode","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-09-28T00:42:22.330Z","log.logger":"api","log.origin":{"file.name":"api/server.go","file.line":68},"message":"Starting stats endpoint","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-09-28T00:42:22.330Z","log.origin":{"file.name":"application/fleet_server_bootstrap.go","file.line":134},"message":"Agent is starting","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-09-28T00:42:22.330Z","log.logger":"api","log.origin":{"file.name":"api/server.go","file.line":70},"message":"Metrics endpoint listening on: /usr/share/elastic-agent/state/data/tmp/elastic-agent.sock (configured: unix:///usr/share/elastic-agent/state/data/tmp/elastic-agent.sock)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-09-28T00:42:22.332Z","log.origin":{"file.name":"application/fleet_server_bootstrap.go","file.line":144},"message":"Agent is stopped","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-09-28T00:42:22.773Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is 22NsDxqk","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-09-28T00:42:22.774Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 1 step(s)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-09-28T00:42:22.830Z","log.origin":{"file.name":"operation/operator.go","file.line":387},"message":"operation 'operation-install' skipped for fleet-server.8.5.0-SNAPSHOT","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-09-28T00:42:22.914Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2022-09-28T00:42:22Z - message: Application: fleet-server--8.5.0-SNAPSHOT[]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-09-28T00:42:22.915Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":66},"message":"Updating internal state","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-09-28T00:42:22.931Z","log.origin":{"file.name":"process/stdlogger.go","file.line":54},"message":"fleet-server stderr: \"{\\\"level\\\":\\\"info\\\",\\\"time\\\":\\\"2022-09-28T00:42:22Z\\\",\\\"message\\\":\\\"No applicable limit for 0 agents, using default.\\\"}\\n{\\\"level\\\":\\\"info\\\",\\\"time\\\":\\\"2022-09-28T00:42:22Z\\\",\\\"message\\\":\\\"No applicable limit for 0 agents, using default.\\\"}\\n\"","agent.console.name":"fleet-server","agent.console.type":"stderr","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-09-28T00:42:23.018Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":792},"message":"Fleet Server - Starting","ecs.version":"1.6.0"}
{"log.level":"warn","@timestamp":"2022-09-28T00:42:24.440Z","log.origin":{"file.name":"status/reporter.go","file.line":325},"message":"Elastic Agent status changed to \"degraded\": \"app fleet-server--8.5.0-SNAPSHOT-382c1ce2: Running on policy with Fleet Server integration: fleet-server-apm-policy; missing config fleet.agent.id (expected during bootstrap process)\"","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-09-28T00:42:24.440Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2022-09-28T00:42:24Z - message: Application: fleet-server--8.5.0-SNAPSHOT[]: State changed to DEGRADED: Running on policy with Fleet Server integration: fleet-server-apm-policy; missing config fleet.agent.id (expected during bootstrap process) - type: 'STATE' - sub_type: 'RUNNING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-09-28T00:42:25.022Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":773},"message":"Fleet Server - Running on policy with Fleet Server integration: fleet-server-apm-policy; missing config fleet.agent.id (expected during bootstrap process)","ecs.version":"1.6.0"}
{"log.level":"warn","@timestamp":"2022-09-28T00:42:25.022Z","log.logger":"tls","log.origin":{"file.name":"tlscommon/tls_config.go","file.line":104},"message":"SSL/TLS verifications disabled.","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-09-28T00:42:25.198Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":471},"message":"Starting enrollment to URL: http://0.0.0.0:8220/","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-09-28T00:42:26.077Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":277},"message":"Elastic Agent has been enrolled; start Elastic Agent","ecs.version":"1.6.0"}
Successfully enrolled the Elastic Agent.
{"log.level":"info","@timestamp":"2022-09-28T00:42:26.078Z","log.origin":{"file.name":"cmd/run.go","file.line":254},"message":"Shutting down Elastic Agent and sending last events...","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-09-28T00:42:26.078Z","log.origin":{"file.name":"operation/operator.go","file.line":302},"message":"waiting for installer of pipeline 'default' to finish","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-09-28T00:42:26.078Z","log.origin":{"file.name":"process/app.go","file.line":179},"message":"Signaling application to stop because of shutdown: fleet-server--8.5.0-SNAPSHOT","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-09-28T00:42:26.579Z","log.origin":{"file.name":"process/app.go","file.line":289},"message":"failed to stop fleet-server: os: process already finished","ecs.version":"1.6.0"}
{"log.level":"warn","@timestamp":"2022-09-28T00:42:27.580Z","log.origin":{"file.name":"status/reporter.go","file.line":325},"message":"Elastic Agent status changed to \"online\": \"\"","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-09-28T00:42:27.580Z","log.origin":{"file.name":"cmd/run.go","file.line":262},"message":"Shutting down completed.","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-09-28T00:42:27.580Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2022-09-28T00:42:27Z - message: Application: fleet-server--8.5.0-SNAPSHOT[]: State changed to STOPPED: Stopped - type: 'STATE' - sub_type: 'STOPPED'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-09-28T00:42:27.580Z","log.logger":"api","log.origin":{"file.name":"api/server.go","file.line":72},"message":"Stats endpoint (/usr/share/elastic-agent/state/data/tmp/elastic-agent.sock) finished: accept unix /usr/share/elastic-agent/state/data/tmp/elastic-agent.sock: use of closed network connection","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-09-28T00:42:27.744Z","log.origin":{"file.name":"cmd/run.go","file.line":202},"message":"APM instrumentation disabled","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-09-28T00:42:27.744Z","log.origin":{"file.name":"application/application.go","file.line":78},"message":"Detecting execution mode","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-09-28T00:42:27.765Z","log.origin":{"file.name":"application/application.go","file.line":102},"message":"Agent is managed by Fleet","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-09-28T00:42:27.765Z","log.origin":{"file.name":"capabilities/capabilities.go","file.line":59},"message":"capabilities file not found in /usr/share/elastic-agent/state/capabilities.yml","ecs.version":"1.6.0"}
{"log.level":"warn","@timestamp":"2022-09-28T00:42:27.766Z","log.logger":"tls","log.origin":{"file.name":"tlscommon/tls_config.go","file.line":104},"message":"SSL/TLS verifications disabled.","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-09-28T00:42:28.218Z","log.logger":"composable.providers.docker","log.origin":{"file.name":"docker/docker.go","file.line":44},"message":"Docker provider skipped, unable to connect: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get \"http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info\": dial unix /var/run/docker.sock: connect: permission denied","ecs.version":"1.6.0"}
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/elastic/elastic-agent/internal/pkg/core/status.(*controller).RegisterLocalComponent(0xc0008bc420, {0x5566c44c1f8e, 0xf})
	github.com/elastic/elastic-agent/internal/pkg/core/status/reporter.go:151 +0x29c
github.com/elastic/elastic-agent/internal/pkg/agent/application/gateway/fleet.newFleetGatewayWithScheduler({0x5566c4e749e8?, 0xc0001d6bc0}, 0xc0002f6850, 0x5566c5c814a0, {0x5566c4e5b348?, 0xc0008e1ad0}, {0x5566c4e62748?, 0xc0008bcd10}, {0x5566c4e5b4c8, 0xc0008ca570}, ...)
	github.com/elastic/elastic-agent/internal/pkg/agent/application/gateway/fleet/fleet_gateway.go:160 +0x135
github.com/elastic/elastic-agent/internal/pkg/agent/application/gateway/fleet.New({0x5566c4e749e8, 0xc0001d6bc0}, 0xc0003c5a70?, {0x5566c4e5b348, 0xc0008e1ad0}, {0x5566c4e62748, 0xc0008bcd10}, {0x5566c4e5b4c8, 0xc0008ca570}, {0x5566c4e62608, ...}, ...)
	github.com/elastic/elastic-agent/internal/pkg/agent/application/gateway/fleet/fleet_gateway.go:110 +0x205
github.com/elastic/elastic-agent/internal/pkg/agent/application.newManaged({0x5566c4e74a20?, 0xc000058018}, 0xc0002f6850, {0x7fb20c2c9898?, 0xc0006495c0}, 0xc00040c590, 0x1?, {0x7fb20c3f8b58?, 0xc0008e1b30}, {0x5566c4e7b788, ...}, ...)
	github.com/elastic/elastic-agent/internal/pkg/agent/application/managed_mode.go:279 +0x1c65
github.com/elastic/elastic-agent/internal/pkg/agent/application.createApplication(0xc0002f6850, {0xc0008da3c0, 0x30}, 0x7fb20c3f8b58?, {0x7fb20c3f8b58, 0xc0008e1b30}, {0x5566c4e7b788, 0xc0008bc420}, {0x5566c4e5b6e8, 0xc00064ae00}, ...)
	github.com/elastic/elastic-agent/internal/pkg/agent/application/application.go:103 +0x2fe
github.com/elastic/elastic-agent/internal/pkg/agent/application.New(0xc00064ae00?, {0x7fb20c3f8b58, 0xc0008e1b30}, {0x5566c4e7b788, 0xc0008bc420}, {0x5566c4e5b6e8, 0xc00064ae00}, 0xc00089eef0?, 0x1?)
	github.com/elastic/elastic-agent/internal/pkg/agent/application/application.go:65 +0x119
github.com/elastic/elastic-agent/internal/pkg/agent/cmd.run(0xc000108160?)
	github.com/elastic/elastic-agent/internal/pkg/agent/cmd/run.go:212 +0xee5
github.com/elastic/elastic-agent/internal/pkg/agent/cmd.runContainerCmd(_, {{{0x0, 0x0}, 0x1, {0x0, 0x0}, 0x0, 0x0, {0x5566c44b4fdf, 0x7}, ...}, ...})
	github.com/elastic/elastic-agent/internal/pkg/agent/cmd/container.go:335 +0x688
github.com/elastic/elastic-agent/internal/pkg/agent/cmd.containerCmd(0xc0004ff710)
	github.com/elastic/elastic-agent/internal/pkg/agent/cmd/container.go:252 +0x765
github.com/elastic/elastic-agent/internal/pkg/agent/cmd.logContainerCmd(0xc0004ff710)
	github.com/elastic/elastic-agent/internal/pkg/agent/cmd/container.go:170 +0x8dc
github.com/elastic/elastic-agent/internal/pkg/agent/cmd.newContainerCommand.func1(0xc000145b80?, {0x5566c44b1d07?, 0x0?, 0x0?})
	github.com/elastic/elastic-agent/internal/pkg/agent/cmd/container.go:137 +0x25
github.com/spf13/cobra.(*Command).execute(0xc000145b80, {0x5566c5d32e60, 0x0, 0x0})
	github.com/spf13/cobra@v1.3.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0xc00085ca00)
	github.com/spf13/cobra@v1.3.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.3.0/command.go:902
main.main()
	github.com/elastic/elastic-agent/main.go:33 +0x179
```
</details>

**Comment by AndersonQ** [comment]
https://github.com/elastic/elastic-agent/pull/1346 fixes that
