### ISSUE TITLE
7.17: Nil pointer dereference in fleet_debian_10_arm64_system_integration E2E test

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#1863]
https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/PR-3252/1/pipeline/590/

```
[2022-11-30T06:26:17.229Z] Nov 30 06:07:29 ip-172-31-8-249 elastic-agent[15774]: 2022-11-30T06:07:29.103Z        INFO        application/application.go:67        Detecting execution mode
[2022-11-30T06:26:17.229Z] Nov 30 06:07:29 ip-172-31-8-249 elastic-agent[15774]: 2022-11-30T06:07:29.104Z        INFO        application/application.go:76        Agent is managed locally
[2022-11-30T06:26:17.229Z] Nov 30 06:07:29 ip-172-31-8-249 elastic-agent[15774]: 2022-11-30T06:07:29.105Z        INFO        capabilities/capabilities.go:59        capabilities file not found in /opt/Elastic/Agent/capabilities.yml
[2022-11-30T06:26:17.229Z] Nov 30 06:07:30 ip-172-31-8-249 elastic-agent[15774]: 2022-11-30T06:07:30.412Z        INFO        [api]        api/server.go:62        Starting stats endpoint
[2022-11-30T06:26:17.229Z] Nov 30 06:07:30 ip-172-31-8-249 elastic-agent[15774]: 2022-11-30T06:07:30.412Z        INFO        application/local_mode.go:168        Agent is starting
[2022-11-30T06:26:17.229Z] Nov 30 06:07:30 ip-172-31-8-249 elastic-agent[15774]: 2022-11-30T06:07:30.412Z        INFO        application/local_mode.go:178        Agent is stopped
[2022-11-30T06:26:17.229Z] Nov 30 06:07:30 ip-172-31-8-249 elastic-agent[15774]: 2022-11-30T06:07:30.413Z        INFO        [api]        api/server.go:64        Metrics endpoint listening on: /opt/Elastic/Agent/data/tmp/elastic-agent.sock (configured: unix:///opt/Elastic/Agent/data/tmp/elastic-agent.sock)
[2022-11-30T06:26:17.230Z] Nov 30 06:07:30 ip-172-31-8-249 elastic-agent[15774]: panic: runtime error: invalid memory address or nil pointer dereference
[2022-11-30T06:26:17.230Z] Nov 30 06:07:30 ip-172-31-8-249 elastic-agent[15774]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xaaaab490f78c]
[2022-11-30T06:26:17.230Z] Nov 30 06:07:30 ip-172-31-8-249 elastic-agent[15774]: goroutine 84 [running]:
[2022-11-30T06:26:17.230Z] Nov 30 06:07:30 ip-172-31-8-249 elastic-agent[15774]: google.golang.org/grpc.(*Server).Serve(0x4000192700?, {0xaaaab5e3a168?, 0x4000717260?})
[2022-11-30T06:26:17.230Z] Nov 30 06:07:30 ip-172-31-8-249 elastic-agent[15774]:         /go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:740 +0x3c
[2022-11-30T06:26:17.230Z] Nov 30 06:07:30 ip-172-31-8-249 elastic-agent[15774]: github.com/elastic/beats/v7/x-pack/elastic-agent/pkg/core/server.(*Server).Start.func1()
[2022-11-30T06:26:17.230Z] Nov 30 06:07:30 ip-172-31-8-249 elastic-agent[15774]:         /go/src/github.com/elastic/beats/x-pack/elastic-agent/pkg/core/server/server.go:159 +0x34
[2022-11-30T06:26:17.230Z] Nov 30 06:07:30 ip-172-31-8-249 elastic-agent[15774]: created by github.com/elastic/beats/v7/x-pack/elastic-agent/pkg/core/server.(*Server).Start
[2022-11-30T06:26:17.230Z] Nov 30 06:07:30 ip-172-31-8-249 elastic-agent[15774]:         /go/src/github.com/elastic/beats/x-pack/elastic-agent/pkg/core/server/server.go:158 +0x364
[2022-11-30T06:26:17.230Z] Nov 30 06:07:30 ip-172-31-8-249 systemd[1]: elastic-agent.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
[2022-11-30T06:26:17.230Z] Nov 30 06:07:30 ip-172-31-8-249 systemd[1]: elastic-agent.service: Failed with result 'exit-code'.
[2022-11-30T06:26:17.230Z] Nov 30 06:09:30 ip-172-31-8-249 systemd[1]: elastic-agent.service: Service RestartSec=2min expired, scheduling restart.
[2022-11-30T06:26:17.230Z] Nov 30 06:09:30 ip-172-31-8-249 systemd[1]: elastic-agent.service: Scheduled restart job, restart counter is at 1.
[2022-11-30T06:26:17.231Z] Nov 30 06:09:30 ip-172-31-8-249 systemd[1]: Stopped Elastic Agent is a unified agent to observe, monitor and protect your system..
[2022-11-30T06:26:17.231Z] Nov 30 06:09:30 ip-172-31-8-249 systemd[1]: Started Elastic Agent is a unified agent to observe, monitor and protect your system..
[2022-11-30T06:26:17.231Z] Nov 30 06:12:34 ip-172-31-8-249 systemd[1]: Stopping Elastic Agent is a unified agent to observe, monitor and protect your system....
[2022-11-30T06:26:17.231Z] Nov 30 06:14:04 ip-172-31-8-249 systemd[1]: elastic-agent.service: State 'stop-sigterm' timed out. Killing.
[2022-11-30T06:26:17.231Z] Nov 30 06:14:04 ip-172-31-8-249 systemd[1]: elastic-agent.service: Killing process 15804 (elastic-agent) with signal SIGKILL.
[2022-11-30T06:26:17.231Z] Nov 30 06:14:04 ip-172-31-8-249 systemd[1]: elastic-agent.service: Killing process 15857 (filebeat) with signal SIGKILL.
[2022-11-30T06:26:17.231Z] Nov 30 06:14:04 ip-172-31-8-249 systemd[1]: elastic-agent.service: Main process exited, code=killed, status=9/KILL
[2022-11-30T06:26:17.231Z] Nov 30 06:14:04 ip-172-31-8-249 systemd[1]: elastic-agent.service: Failed with result 'timeout'.
[2022-11-30T06:26:17.232Z] Nov 30 06:14:04 ip-172-31-8-249 systemd[1]: Stopped Elastic Agent is a unified agent to observe, monitor and 
```

Full logs are attached. 

[e2e_logs.txt](https://github.com/elastic/elastic-agent/files/10133614/e2e_logs.txt)

**Comment by cmacknz** [comment]
Originally triggered by this PR https://github.com/elastic/e2e-testing/pull/3252

**Comment by cmacknz** [comment]
In gRPC this is the code path that is segfaulting:

```go
func (s *Server) Serve(lis net.Listener) error {
	s.mu.Lock()
```

On the agent side it is:

```go
	// start serving GRPC connections
	go func() {
		err := s.server.Serve(lis)
		if err != nil {
			s.logger.Errorf("error listening for GRPC: %s", err)
		}
	}()
```

**Comment by cmacknz** [comment]
My guess is that something called `Stop` before the `Serve` goroutine above actually started running: https://github.com/elastic/beats/blob/a2289487438f57f724e1d836f3738cadd62fd477/x-pack/elastic-agent/pkg/core/server/server.go#L133-L182

```go
// Start starts the GRPC endpoint and accepts new connections.
func (s *Server) Start() error {
	if s.server != nil {
		// already started
		return nil
	}

	lis, err := net.Listen("tcp", s.listenAddr)
	if err != nil {
		return err
	}
	s.listener = lis
	certPool := x509.NewCertPool()
	if ok := certPool.AppendCertsFromPEM(s.ca.Crt()); !ok {
		return errors.New("failed to append root CA", errors.TypeSecurity)
	}
	creds := credentials.NewTLS(&tls.Config{
		ClientAuth:     tls.RequireAndVerifyClientCert,
		ClientCAs:      certPool,
		GetCertificate: s.getCertificate,
	})
	s.server = grpc.NewServer(grpc.Creds(creds))
	proto.RegisterElasticAgentServer(s.server, s)

	// start serving GRPC connections
	go func() {
		err := s.server.Serve(lis)
		if err != nil {
			s.logger.Errorf("error listening for GRPC: %s", err)
		}
	}()

	// start the watchdog
	s.watchdogDone = make(chan bool)
	s.watchdogWG.Add(1)
	go s.watchdog()

	return nil
}

// Stop stops the GRPC endpoint.
func (s *Server) Stop() {
	if s.server != nil {
		close(s.watchdogDone)
		s.server.Stop()
		s.server = nil
		s.listener = nil
		s.watchdogWG.Wait()
	}
}
```

**Comment by cmacknz** [comment]
I think this is very likely looking at the agent logs:

```
[2022-11-30T06:26:17.229Z] Nov 30 06:07:30 ip-172-31-8-249 elastic-agent[15774]: 2022-11-30T06:07:30.412Z        INFO        application/local_mode.go:168        Agent is starting
[2022-11-30T06:26:17.229Z] Nov 30 06:07:30 ip-172-31-8-249 elastic-agent[15774]: 2022-11-30T06:07:30.412Z        INFO        application/local_mode.go:178        Agent is stopped
```

Likely this is caused by the agent starting and stopping rapidly. That may be the real problem in these tests, and this is just a symptom of it.

**Comment by cmacknz** [comment]
@AndersonQ FYI, I think this is causing occasional failures in the E2E tests for 7.17

**Comment by cachedout** [comment]
FYI, this appears to be blocking QA Source, per https://github.com/elastic/e2e-testing/issues/3236#issue-1461662870

**Comment by AndersonQ** [comment]
I opened a PR that should fix it: https://github.com/elastic/beats/pull/33937
If I'm not mistaken about how the the go scheduler works, there could still be possible to have a panic, but now much more unlikely. This should be enough for this rare corner case.

**Comment by AndersonQ** [comment]
merged https://github.com/elastic/beats/pull/33937, it should fix this issue.
