### ISSUE TITLE
Nil reference on policy change

### ISSUE THREAD

**Issue by michalpristas** [elastic/elastic-agent#2018]
When trying to reproduce reopened #1926 i encountered occasional nil reference here:
```
Unit state changed log-default-logfile-system-dfb73c57-14fc-4724-83d7-3b34fabed84a (STARTING->FAILED): [output unit has no config]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x1049cb690]
goroutine 2182 [running]:
github.com/elastic/beats/v7/x-pack/metricbeat/cmd.metricbeatCfg(0x0, 0xc001282968?)
github.com/elastic/beats/v7/x-pack/metricbeat/cmd/agent.go:25 +0x50
github.com/elastic/beats/v7/x-pack/libbeat/management.(*TransformRegister).Transform(0x5?, 0x19?, 0x200000002?)
github.com/elastic/beats/v7/x-pack/libbeat/management/generate.go:60 +0x103
github.com/elastic/beats/v7/x-pack/libbeat/management.generateBeatConfig(0xc001697190?, 0xc001282a98?)
github.com/elastic/beats/v7/x-pack/libbeat/management/generate.go:232 +0x26
github.com/elastic/beats/v7/x-pack/libbeat/management.(*BeatV2Manager).reloadInputs(0xc000a23440, {0xc00028da20, 0x1, 0x0?})
github.com/elastic/beats/v7/x-pack/libbeat/management/managerV2.go:540 +0x155
github.com/elastic/beats/v7/x-pack/libbeat/management.(*BeatV2Manager).reload(0xc000a23440, 0xc001282da8?)
github.com/elastic/beats/v7/x-pack/libbeat/management/managerV2.go:450 +0x56b
github.com/elastic/beats/v7/x-pack/libbeat/management.(*BeatV2Manager).unitListen(0xc000a23440)
github.com/elastic/beats/v7/x-pack/libbeat/management/managerV2.go:379 +0x405
created by github.com/elastic/beats/v7/x-pack/libbeat/management.(*BeatV2Manager).Start
github.com/elastic/beats/v7/x-pack/libbeat/management/managerV2.go:178 +0x116
``` 

this resulted in agent reporting not healthy with `1 or more components/units in a failed state`

**Comment by cmacknz** [comment]
This is happening because the Metricbeat Beat configuration transformation does not guard against the `rawIn` variable being `nil`:

https://github.com/elastic/beats/blob/d8204a2c9f76c5abecca3af77136cea4901d0ae6/x-pack/metricbeat/cmd/agent.go#L25
```go
module := strings.Split(rawIn.Type, "/")[0]
```

We would want `module := strings.Split(rawIn.GetType(), "/")[0]` instead.

We would also want to audit all of the beat configuration transformations for nil safety, not just Metricbeat.

Fundamentally, I'm not sure we should even be calling these functions when the input is `nil` because they can't reasonably do anything with it.

The real bug may be that we are receiving `nil` input unit configurations. We guard against this for output changes for example:

https://github.com/elastic/beats/blob/d8204a2c9f76c5abecca3af77136cea4901d0ae6/x-pack/libbeat/management/managerV2.go#L492-L499
