### ISSUE TITLE
golangci-lint issues with Go 1.18 issues on Elastic-Agent

### ISSUE THREAD

**Issue by ph** [elastic/elastic-agent#224]
Found in https://github.com/elastic/elastic-agent/pull/207
```
Run golangci/golangci-lint-action@v2
prepare environment
run golangci-lint
  Running [/home/runner/golangci-lint-1.44.2-linux-amd64/golangci-lint run --out-format=github-actions --new-from-patch=/tmp/tmp-1568-Gs1g2dO72EnP/pull.patch --new=false --new-from-rev= --timeout=5m] in [] ...
  panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt
  
  goroutine 1 [running]:
  github.com/go-critic/go-critic/checkers.init.22()
  	github.com/go-critic/go-critic@v0.6.2/checkers/embedded_rules.go:46 +0x4b4
  
  Error: golangci-lint exit with code 2
  Ran golangci-lint in 1[33](https://github.com/elastic/elastic-agent/runs/5576562809?check_suite_focus=true#step:5:33)93ms

**Comment by jlind23** [comment]
go version has been updated hence closing
