### ISSUE TITLE
Deadlock on startup if the agent cannot bind to its configured network port

### ISSUE THREAD

**Issue by faec** [elastic/elastic-agent#2310]
- Version: repository head
- Operating System: macOS 12.6.3 (reproduced on both intel and arm)
- Steps to Reproduce:
  * Build the agent: `EXTERNAL=false PLATFORMS=darwin/amd64 PACKAGES=TarGz mage dev:package`
  * Unpack the resulting tarball: `tar zxvf build/distributions/elastic-agent-8.8.0-darwin-x86_64.tar.gz`
  * If desired, edit `elastic-agent.yml` to point to a live elasticsearch (this is probably optional since the failure seems to happen before any output setup)
  * Run the agent from the untarred directory (on darwin this requires root): `sudo ./elastic-agent`

At this point the agent deadlocks after only a fairly small number of log lines. If you try to quit with ctrl-c, it will say `"Shutting down Elastic Agent and sending last events..."`, however it will never actually terminate until a `kill -9` is run on its child process.

This doesn't appear to reproduce on Linux, regardless of whether it's run as root.

The complete logs up to the point it deadlocks are:

```
{"log.level":"info","@timestamp":"2023-02-22T16:04:38.103-0500","log.origin":{"file.name":"cmd/run.go","file.line":186},"message":"Elastic Agent has been built with security disabled. Elastic Agent will not verify signatures of upgrade artifact.","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-22T16:04:38.104-0500","log.origin":{"file.name":"cmd/run.go","file.line":207},"message":"APM instrumentation disabled","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-22T16:04:38.105-0500","log.origin":{"file.name":"application/application.go","file.line":45},"message":"Gathered system information","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-22T16:04:38.128-0500","log.origin":{"file.name":"application/application.go","file.line":51},"message":"Detected available inputs and outputs","log":{"source":"elastic-agent"},"inputs":["syslog","synthetics/http","linux/metrics","aws/metrics","syncgateway/metrics","etcd/metrics","cloudfoundry","tcp","windows/metrics","activemq/metrics","prometheus/metrics","journald","kibana/metrics","postgresql/metrics","redis/metrics","mongodb/metrics","gcs","kubernetes/metrics","http/metrics","zookeeper/metrics","docker","log","mysql/metrics","uwsgi/metrics","awsfargate/metrics","kafka/metrics","nginx/metrics","http_endpoint","synthetics/icmp","memcached/metrics","winlog","udp","system/metrics","nats/metrics","stan/metrics","statsd/metrics","container","cel","mqtt","beat/metrics","azure-blob-storage","kafka","o365audit","apache/metrics","iis/metrics","httpjson","filestream","elasticsearch/metrics","enterprisesearch/metrics","cloudfoundry/metrics","sql/metrics","redis","oracle/metrics","azure-eventhub","jolokia/metrics","rabbitmq/metrics","unix","gcp-pubsub","azure/metrics","gcp/metrics","traefik/metrics","vsphere/metrics","osquery","aws-s3","entity-analytics","netflow","synthetics/browser","synthetics/tcp","logstash/metrics","haproxy/metrics","cometd","docker/metrics","containerd/metrics","mssql/metrics","aws-cloudwatch"],"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-22T16:04:38.128-0500","log.origin":{"file.name":"capabilities/capabilities.go","file.line":54},"message":"Capabilities file not found in /Users/fae/go/src/github.com/elastic/elastic-agent/elastic-agent-8.8.0-darwin-x86_64/capabilities.yml","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-22T16:04:38.128-0500","log.origin":{"file.name":"application/application.go","file.line":57},"message":"Determined allowed capabilities","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-22T16:04:38.290-0500","log.origin":{"file.name":"application/application.go","file.line":88},"message":"Parsed configuration and determined agent is managed locally","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-22T16:04:38.293-0500","log.logger":"api","log.origin":{"file.name":"api/server.go","file.line":68},"message":"Starting stats endpoint","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-22T16:04:38.293-0500","log.logger":"api","log.origin":{"file.name":"api/server.go","file.line":70},"message":"Metrics endpoint listening on: 127.0.0.1:6791 (configured: http://localhost:6791)","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-22T16:04:38.294-0500","log.origin":{"file.name":"application/periodic.go","file.line":93},"message":"Configuration changes detected","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
```

**Comment by fearful-symmetry** [comment]
I was able to reproduce this, here's the stack trace from `kill -6`: 
```
[1]    17750 abort      sudo ./elastic-agent -d '*'
SIGABRT: abort
PC=0x1a89b184c m=0 sigcode=0

goroutine 0 [idle]:
runtime.pthread_cond_wait(0x105991b60, 0x105991b20)
	/usr/local/go/src/runtime/sys_darwin.go:449 +0x20
runtime.semasleep(0xffffffffffffffff)
	/usr/local/go/src/runtime/os_darwin.go:66 +0x70
runtime.notesleep(0x105991928)
	/usr/local/go/src/runtime/lock_sema.go:181 +0xc8
runtime.mPark()
	/usr/local/go/src/runtime/proc.go:1449 +0x20
runtime.stoplockedm()
	/usr/local/go/src/runtime/proc.go:2430 +0x64
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:3127 +0x38
runtime.park_m(0x130?)
	/usr/local/go/src/runtime/proc.go:3344 +0x118
runtime.mcall()
	/usr/local/go/src/runtime/asm_arm64.s:190 +0x54

goroutine 1 [select, 13 minutes]:
github.com/elastic/elastic-agent/internal/pkg/agent/cmd.run(0x0, {0x0, 0x0, 0x0})
	/go/src/github.com/elastic/elastic-agent/internal/pkg/agent/cmd/run.go:247 +0x1be8
github.com/elastic/elastic-agent/internal/pkg/agent/cmd.newRunCommandWithArgs.func1(0x14000662280, {0x140006617c0, 0x0, 0x2})
	/go/src/github.com/elastic/elastic-agent/internal/pkg/agent/cmd/run.go:64 +0x38
github.com/spf13/cobra.(*Command).execute(0x14000662280, {0x1400004e1c0, 0x2, 0x2})
	/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x854
github.com/spf13/cobra.(*Command).ExecuteC(0x14000662280)
	/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x6f0
github.com/spf13/cobra.(*Command).Execute(0x14000662280)
	/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902 +0x30
main.main()
	/go/src/github.com/elastic/elastic-agent/main.go:33 +0x280

goroutine 97 [IO wait, 13 minutes]:
internal/poll.runtime_pollWait(0x0?, 0x72)
	/usr/local/go/src/runtime/netpoll.go:302 +0x48
internal/poll.(*pollDesc).wait(0x140009cc498, 0x72, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:83 +0x88
internal/poll.(*pollDesc).waitRead(0x140009cc498, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:88 +0x38
internal/poll.(*FD).Accept(0x140009cc480)
	/usr/local/go/src/internal/poll/fd_unix.go:614 +0x32c
net.(*netFD).accept(0x140009cc480)
	/usr/local/go/src/net/fd_unix.go:172 +0x4c
net.(*TCPListener).accept(0x140006c15f0)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x44
net.(*TCPListener).Accept(0x140006c15f0)
	/usr/local/go/src/net/tcpsock.go:288 +0x50
net/http.(*Server).Serve(0x140008da000, {0x104c5d928, 0x140006c15f0})
	/usr/local/go/src/net/http/server.go:3039 +0x3ec
net/http.Serve({0x104c5d928, 0x140006c15f0}, {0x104c49898, 0x140009cf0c0})
	/usr/local/go/src/net/http/server.go:2543 +0xd4
github.com/elastic/elastic-agent-libs/api.(*Server).Start.func1({0x104c5d928, 0x140006c15f0})
	/go/pkg/mod/github.com/elastic/elastic-agent-libs@v0.2.16/api/server.go:71 +0x19c
created by github.com/elastic/elastic-agent-libs/api.(*Server).Start
	/go/pkg/mod/github.com/elastic/elastic-agent-libs@v0.2.16/api/server.go:69 +0x17c

goroutine 98 [IO wait, 13 minutes]:
internal/poll.runtime_pollWait(0x0?, 0x72)
	/usr/local/go/src/runtime/netpoll.go:302 +0x48
internal/poll.(*pollDesc).wait(0x140009cc518, 0x72, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:83 +0x88
internal/poll.(*pollDesc).waitRead(0x140009cc518, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:88 +0x38
internal/poll.(*FD).Accept(0x140009cc500)
	/usr/local/go/src/internal/poll/fd_unix.go:614 +0x32c
net.(*netFD).accept(0x140009cc500)
	/usr/local/go/src/net/fd_unix.go:172 +0x4c
net.(*UnixListener).accept(0x1400038a240)
	/usr/local/go/src/net/unixsock_posix.go:166 +0x44
net.(*UnixListener).Accept(0x1400038a240)
	/usr/local/go/src/net/unixsock.go:260 +0x50
google.golang.org/grpc.(*Server).Serve(0x1400096a380, {0x104c5d958, 0x1400038a240})
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:780 +0x47c
github.com/elastic/elastic-agent/internal/pkg/agent/control/v2/server.(*Server).Start.func1()
	/go/src/github.com/elastic/elastic-agent/internal/pkg/agent/control/v2/server/server.go:87 +0x50
created by github.com/elastic/elastic-agent/internal/pkg/agent/control/v2/server.(*Server).Start
	/go/src/github.com/elastic/elastic-agent/internal/pkg/agent/control/v2/server/server.go:86 +0x4f8

goroutine 27 [select, 13 minutes]:
github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).Run.func1()
	/go/src/github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator/coordinator.go:349 +0x164
created by github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).Run
	/go/src/github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator/coordinator.go:344 +0xc0

goroutine 8 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x105990be0)
	/go/pkg/mod/k8s.io/klog/v2@v2.30.0/klog.go:1181 +0x58
created by k8s.io/klog/v2.init.0
	/go/pkg/mod/k8s.io/klog/v2@v2.30.0/klog.go:420 +0x18c

goroutine 26 [syscall, 13 minutes]:
os/signal.signal_recv()
	/usr/local/go/src/runtime/sigqueue.go:148 +0x30
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x28
created by os/signal.Notify.func1.1
	/usr/local/go/src/os/signal/signal.go:151 +0x40

goroutine 10 [chan receive, 13 minutes]:
github.com/elastic/elastic-agent-libs/service.HandleSignals.func1()
	/go/pkg/mod/github.com/elastic/elastic-agent-libs@v0.2.16/service/service.go:50 +0x54
created by github.com/elastic/elastic-agent-libs/service.HandleSignals
	/go/pkg/mod/github.com/elastic/elastic-agent-libs@v0.2.16/service/service.go:49 +0x240

goroutine 99 [chan receive, 13 minutes]:
github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).runner(0x1400047c000, {0x104c5e7d8, 0x14000814000})
	/go/src/github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator/coordinator.go:581 +0x1308
github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).Run(0x1400047c000, {0x104c5e7d8, 0x14000222e40})
	/go/src/github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator/coordinator.go:412 +0x12c
github.com/elastic/elastic-agent/internal/pkg/agent/cmd.run.func6()
	/go/src/github.com/elastic/elastic-agent/internal/pkg/agent/cmd/run.go:235 +0x54
created by github.com/elastic/elastic-agent/internal/pkg/agent/cmd.run
	/go/src/github.com/elastic/elastic-agent/internal/pkg/agent/cmd/run.go:234 +0x195c

goroutine 29 [chan send, 13 minutes]:
github.com/elastic/elastic-agent/internal/pkg/agent/application.(*periodic).work(0x140009ce1c0)
	/go/src/github.com/elastic/elastic-agent/internal/pkg/agent/application/periodic.go:113 +0xa84
github.com/elastic/elastic-agent/internal/pkg/agent/application.(*periodic).Run(0x140009ce1c0, {0x104c5e7d8, 0x14000814000})
	/go/src/github.com/elastic/elastic-agent/internal/pkg/agent/application/periodic.go:31 +0x3c
github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).runner.func2({0x10cf60ac0, 0x140009ce1c0})
	/go/src/github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator/coordinator.go:562 +0x60
created by github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).runner
	/go/src/github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator/coordinator.go:561 +0x3f4

goroutine 30 [chan send, 13 minutes]:
github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).runner.func3({0x10cf60ae8, 0x140009d5e90})
	/go/src/github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator/coordinator.go:573 +0x8c
created by github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).runner
	/go/src/github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator/coordinator.go:570 +0x5a4

goroutine 35 [chan receive, 13 minutes]:
github.com/elastic/elastic-agent/pkg/component/runtime.(*Manager).SubscribeAll.func2()
	/go/src/github.com/elastic/elastic-agent/pkg/component/runtime/manager.go:527 +0x64
created by github.com/elastic/elastic-agent/pkg/component/runtime.(*Manager).SubscribeAll
	/go/src/github.com/elastic/elastic-agent/pkg/component/runtime/manager.go:526 +0x530

goroutine 147 [IO wait, 13 minutes]:
internal/poll.runtime_pollWait(0x104c4bc18?, 0x72)
	/usr/local/go/src/runtime/netpoll.go:302 +0x48
internal/poll.(*pollDesc).wait(0x14000550118, 0x72, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:83 +0x88
internal/poll.(*pollDesc).waitRead(0x14000550118, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:88 +0x38
internal/poll.(*FD).Read(0x14000550100, {0x14000572000, 0x1000, 0x1000})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x33c
net.(*netFD).Read(0x14000550100, {0x14000572000, 0x1000, 0x1000})
	/usr/local/go/src/net/fd_posix.go:55 +0x54
net.(*conn).Read(0x14000616040, {0x14000572000, 0x1000, 0x1000})
	/usr/local/go/src/net/net.go:183 +0x70
net/http.(*persistConn).Read(0x14000137c20, {0x14000572000, 0x1000, 0x1000})
	/usr/local/go/src/net/http/transport.go:1929 +0x188
bufio.(*Reader).fill(0x14000274b40)
	/usr/local/go/src/bufio/bufio.go:106 +0x234
bufio.(*Reader).Peek(0x14000274b40, 0x1)
	/usr/local/go/src/bufio/bufio.go:144 +0x150
net/http.(*persistConn).readLoop(0x14000137c20)
	/usr/local/go/src/net/http/transport.go:2093 +0x1f0
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1750 +0x1fa0

goroutine 148 [select, 13 minutes]:
net/http.(*persistConn).writeLoop(0x14000137c20)
	/usr/local/go/src/net/http/transport.go:2392 +0x104
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1751 +0x2000
```

**Comment by cmacknz** [comment]
> Run the agent from the untarred directory (on darwin this requires root): sudo ./elastic-agent

Typically you'd run `elastic-agent install` first, which I hope doesn't have this problem.


The coordinator seems to be waiting for an error from `configErrCh` but in a way that suggests the runtime manager has exited since it would have to have received from that channel first:

```
github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).runner(0x1400047c000, {0x104c5e7d8, 0x14000814000})
	/go/src/github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator/coordinator.go:581 +0x1308
```

https://github.com/elastic/elastic-agent/blob/fd26c38120077a91ce81a0caeacf3b6ba7d0abce/internal/pkg/agent/application/coordinator/coordinator.go#L576-L581

**Comment by cmacknz** [comment]
If you try to install the agent does it succeed?

**Comment by fearful-symmetry** [comment]
Okay, so here's the actual issue. Had to add a debug line:
```
runtime manager returned error: error listening on localhost:6789: listen tcp 127.0.0.1:6789: bind: address already in use
```

When the runtime manager fails at this point in startup, it triggers a deadock. As Craig pointed out, we're waiting on `configErr := <-configErrCh `, however, the configWatcher that sends to that channel is stuck, as it's waiting on this channel send:
```
p.ch <- &localConfigChange{cfg}
````

The only thing that reads from that channel is the main coordinator loop, which is itself waiting on the `configErrCh`

**Comment by fearful-symmetry** [comment]
No idea what's going on with `localhost:6789`, however since Fae and I could only trigger this on our laptops (and not the linux test server that lives in my closet) I'm guessing the IT managed elastic-agent install is using that port.

**Comment by fearful-symmetry** [comment]
Ah, it's this: 
```
# agent.grpc:
#   # listen address for the GRPC server that spawned processes connect back to.
#   address: localhost
#   # port for the GRPC server that spawned processes connect back to.
#   port: 6789
```

**Comment by cmacknz** [comment]
This was going to be my guess. Running the agent twice on the same machine isn't something we support or test.

The elastic-agent install command will detect if there is an existing installation. Running the agent out of a local directory skips this check. 

We should convert the debug line about the port conflict into an error to make this more obvious in the future.

**Comment by fearful-symmetry** [comment]
@cmacknz it is an error, it just doesn't get reported because of the deadlock that happens if the listen call fails, hence me having to add a debug line manually. Without the deadlock, agent would shut down and report the error.

**Comment by faec** [comment]
Yeah, it looks like this would produce a deadlock on any system where it couldn't get its preferred network port, regardless of whether another agent was the cause. I'm now able to run on darwin without a code fix by explicitly configuring the network port to something else.

**Comment by prockwin** [comment]
Same problem on windows, beats continuously write erros and load cpu and disk if another program listen 6789 port
agent.retry does not affect the recording of these errors to avoid loading

`{"log.level":"error","@timestamp":"2023-03-06T12:27:56.527+0500","log.logger":"centralmgmt.fleet","log.origin":{"file.name":"management/manager.go","file.line":250},"message":"elastic-agent-client got error: rpc error: code = Unavailable desc = connection error: desc = \"transport: authentication handshake failed: tls: first record does not look like a TLS handshake\"","service.name":"filebeat","ecs.version":"1.6.0"}`
