### ISSUE TITLE
Harvester crashed with: harvester panic with: close of closed channel

### ISSUE THREAD

**Issue by rgarcia89** [elastic/elastic-agent#2329]
Please post all questions and issues concerning the Elastic Agent on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: 8.6.2
- Operating System: Kubernetes v1.24.9
- Discuss Forum URL:
- Steps to Reproduce: no idea

I get to see every few minutes the following panic log:

```
Harvester crashed with: harvester panic with: close of closed channel
goroutine 75500 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.startHarvester.func1.1()
	github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile/harvester.go:167 +0x78
panic({0x55ee15af5780, 0x55ee160bd050})
	runtime/panic.go:844 +0x258
github.com/elastic/beats/v7/libbeat/processors/add_kubernetes_metadata.(*cache).stop(...)
	github.com/elastic/beats/v7/libbeat/processors/add_kubernetes_metadata/cache.go:97
github.com/elastic/beats/v7/libbeat/processors/add_kubernetes_metadata.(*kubernetesAnnotator).Close(0xc0017842c0?)
	github.com/elastic/beats/v7/libbeat/processors/add_kubernetes_metadata/kubernetes.go:311 +0x4f
github.com/elastic/beats/v7/libbeat/processors.Close(...)
	github.com/elastic/beats/v7/libbeat/processors/processor.go:58
github.com/elastic/beats/v7/libbeat/publisher/processing.(*group).Close(0x5?)
	github.com/elastic/beats/v7/libbeat/publisher/processing/processors.go:96 +0x159
github.com/elastic/beats/v7/libbeat/processors.Close(...)
	github.com/elastic/beats/v7/libbeat/processors/processor.go:58
github.com/elastic/beats/v7/libbeat/publisher/processing.(*group).Close(0x0?)
	github.com/elastic/beats/v7/libbeat/publisher/processing/processors.go:96 +0x159
github.com/elastic/beats/v7/libbeat/processors.Close(...)
	github.com/elastic/beats/v7/libbeat/processors/processor.go:58
github.com/elastic/beats/v7/libbeat/publisher/pipeline.(*client).Close.func1()
	github.com/elastic/beats/v7/libbeat/publisher/pipeline/client.go:167 +0x2df
sync.(*Once).doSlow(0x0?, 0x0?)
	sync/once.go:68 +0xc2
sync.(*Once).Do(...)
	sync/once.go:59
github.com/elastic/beats/v7/libbeat/publisher/pipeline.(*client).Close(0x55ee13afc466?)
	github.com/elastic/beats/v7/libbeat/publisher/pipeline/client.go:148 +0x59
github.com/elastic/beats/v7/filebeat/beater.(*countingClient).Close(0x55ee13afc3df?)
	github.com/elastic/beats/v7/filebeat/beater/channels.go:145 +0x22
github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.startHarvester.func1({0x55ee16102508?, 0xc0011d1a40})
	github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile/harvester.go:219 +0x929
github.com/elastic/go-concert/unison.(*TaskGroup).Go.func1()
	github.com/elastic/go-concert@v0.2.0/unison/taskgroup.go:163 +0xc3
created by github.com/elastic/go-concert/unison.(*TaskGroup).Go
	github.com/elastic/go-concert@v0.2.0/unison/taskgroup.go:159 +0xca
```

**Comment by cmacknz** [comment]
Duplicate of https://github.com/elastic/beats/issues/34219, currently scheduled for release in 8.7.0
