### ISSUE TITLE
`mage integration:test` fails with cryptic error, apperent issue with OGC

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/elastic-agent#2794]
Right now, for me, `mage integration:test` is failing with this error:

```
>>> Bring down instances through ogc
Error: failed to run ogc down: docker run exited with code: 1
```

After a bit of digging, I figured out it was trying to run this:
```
docker run --rm -e GOOGLE_APPLICATION_SERVICE_ACCOUNT=[name] -e GOOGLE_APPLICATION_CREDENTIALS=/root/agent-testing-service-token.json -e GOOGLE_PROJECT=elastic-platform-ingest -e GOOGLE_DATACENTER=us-central1-a -v /home/alexk/.config/gcloud/agent-testing-service-token.json:/root/agent-testing-service-token.json -v /home/alexk/go/src/github.com/elastic/elastic-agent:/home/alexk/go/src/github.com/elastic/elastic-agent -w /home/alexk/go/src/github.com/elastic/elastic-agent docker.io/gorambo/ogc:latest -- ogc -v down agent-integration
```

Tried running that command myself, with the following result:

```
Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/peewee.py", line 3246, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: no such table: layouts

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/bin/ogc", line 8, in <module>
    sys.exit(start())
             ^^^^^^^
  File "/venv/lib/python3.11/site-packages/ogc/commands/base.py", line 27, in start
    cli()
  File "/venv/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/ogc/commands/down.py", line 34, in down
    _layouts: list[layout.LayoutModel] = [
                                         ^
  File "/venv/lib/python3.11/site-packages/peewee.py", line 7107, in __iter__
    self.execute()
  File "/venv/lib/python3.11/site-packages/peewee.py", line 1966, in inner
    return method(self, database, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/peewee.py", line 2037, in execute
    return self._execute(database)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/peewee.py", line 2210, in _execute
    cursor = database.execute(self)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/peewee.py", line 3254, in execute
    return self.execute_sql(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/peewee.py", line 3244, in execute_sql
    with __exception_wrapper__:
  File "/venv/lib/python3.11/site-packages/peewee.py", line 3014, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/venv/lib/python3.11/site-packages/peewee.py", line 192, in reraise
    raise value.with_traceback(tb)
  File "/venv/lib/python3.11/site-packages/peewee.py", line 3246, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: no such table: layouts
```

I don't really have enough context with [ogc](https://github.com/adam-stokes/ogc) to know what's going on here.

**Comment by pierrehilbert** [comment]
@adam-stokes / @blakerouse could you please have a look?

**Comment by fearful-symmetry** [comment]
@blakerouse already tried that, it's the latest image.

**Comment by blakerouse** [comment]
@fearful-symmetry okay, thanks! maybe try to remove the `.ogc-cache` see if that un-blocks you. 

@adam-stokes can you look at what ogc is complaining about?

**Comment by ycombinator** [comment]
Clearing `.ogc-cache` did the trick.  Thanks @blakerouse.  I'll add this as a tip to https://github.com/elastic/elastic-agent/blob/main/docs/test-framework-dev-guide.md.

**Comment by fearful-symmetry** [comment]
@ycombinator do we want to open a separate issue for clearing that during the `integration:clean` step or something?
