### ISSUE TITLE
Flaky TestCoordinatorShutdownErrorAllResponses

### ISSUE THREAD

**Issue by leehinman** [elastic/elastic-agent#3538]
## Flaky Test

* **Test Name:** TestCoordinatorShutdownErrorAllResponses
* **Link:** https://github.com/elastic/elastic-agent/blob/2201b6d5499ac84a35b271a9bc5898fb4da3d1df/internal/pkg/agent/application/coordinator/coordinator_test.go#L337
* **Branch:** main, https://github.com/elastic/elastic-agent/pull/3526
* **Artifact Link:** If available, attach the generated zip artifact associated with the stack trace for this failure.
* **Notes:** Additional details about the test. e.g. theory as to failure cause

### Stack Trace

```
running tests:

[2023-10-05T14:03:25.292Z] 	TestCoordinatorShutdownErrorAllResponses (9m51s)

[2023-10-05T14:03:25.292Z] 

[2023-10-05T14:03:25.292Z] goroutine 301 [running]:

[2023-10-05T14:03:25.292Z] testing.(*M).startAlarm.func1()

[2023-10-05T14:03:25.292Z] 	C:/Users/jenkins/workspace/_agent_elastic-agent-mbp_PR-3526/.gvm/versions/go1.20.8.windows.amd64/src/testing/testing.go:2241 +0x219

[2023-10-05T14:03:25.292Z] created by time.goFunc

[2023-10-05T14:03:25.292Z] 	C:/Users/jenkins/workspace/_agent_elastic-agent-mbp_PR-3526/.gvm/versions/go1.20.8.windows.amd64/src/time/sleep.go:176 +0x48

[2023-10-05T14:03:25.292Z] 

[2023-10-05T14:03:25.292Z] goroutine 1 [chan receive, 9 minutes]:

[2023-10-05T14:03:25.292Z] testing.(*T).Run(0xc000544340, {0x15be59c, 0x28}, 0x15f4418)

[2023-10-05T14:03:25.292Z] 	C:/Users/jenkins/workspace/_agent_elastic-agent-mbp_PR-3526/.gvm/versions/go1.20.8.windows.amd64/src/testing/testing.go:1630 +0x82e

[2023-10-05T14:03:25.292Z] testing.runTests.func1(0x0?)

[2023-10-05T14:03:25.292Z] 	C:/Users/jenkins/workspace/_agent_elastic-agent-mbp_PR-3526/.gvm/versions/go1.20.8.windows.amd64/src/testing/testing.go:2036 +0x8e

[2023-10-05T14:03:25.292Z] testing.tRunner(0xc000544340, 0xc00083fb48)

[2023-10-05T14:03:25.292Z] 	C:/Users/jenkins/workspace/_agent_elastic-agent-mbp_PR-3526/.gvm/versions/go1.20.8.windows.amd64/src/testing/testing.go:1576 +0x217

[2023-10-05T14:03:25.292Z] testing.runTests(0xc0007c4320?, {0x1f0af40, 0x1f, 0x1f}, {0x1c?, 0x4b0499?, 0x1f19a40?})

[2023-10-05T14:03:25.292Z] 	C:/Users/jenkins/workspace/_agent_elastic-agent-mbp_PR-3526/.gvm/versions/go1.20.8.windows.amd64/src/testing/testing.go:2034 +0x87d

[2023-10-05T14:03:25.292Z] testing.(*M).Run(0xc0007c4320)

[2023-10-05T14:03:25.292Z] 	C:/Users/jenkins/workspace/_agent_elastic-agent-mbp_PR-3526/.gvm/versions/go1.20.8.windows.amd64/src/testing/testing.go:1906 +0xb45

[2023-10-05T14:03:25.292Z] main.main()

[2023-10-05T14:03:25.292Z] 	_testmain.go:107 +0x2ea

[2023-10-05T14:03:25.292Z] 

[2023-10-05T14:03:25.292Z] goroutine 24 [select]:

[2023-10-05T14:03:25.292Z] go.elastic.co/apm.(*Tracer).loop(0xc0004fa000)

[2023-10-05T14:03:25.292Z] 	C:/Users/jenkins/workspace/_agent_elastic-agent-mbp_PR-3526/pkg/mod/go.elastic.co/apm@v1.15.0/tracer.go:975 +0x1576

[2023-10-05T14:03:25.292Z] created by go.elastic.co/apm.newTracer

[2023-10-05T14:03:25.293Z] 	C:/Users/jenkins/workspace/_agent_elastic-agent-mbp_PR-3526/pkg/mod/go.elastic.co/apm@v1.15.0/tracer.go:496 +0x1645

[2023-10-05T14:03:25.293Z] 

[2023-10-05T14:03:25.293Z] goroutine 9 [chan receive]:

[2023-10-05T14:03:25.293Z] go.elastic.co/apm.(*Tracer).loop.func2()

[2023-10-05T14:03:25.293Z] 	C:/Users/jenkins/workspace/_agent_elastic-agent-mbp_PR-3526/pkg/mod/go.elastic.co/apm@v1.15.0/tracer.go:878 +0x2e5

[2023-10-05T14:03:25.293Z] created by go.elastic.co/apm.(*Tracer).loop

[2023-10-05T14:03:25.293Z] 	C:/Users/jenkins/workspace/_agent_elastic-agent-mbp_PR-3526/pkg/mod/go.elastic.co/apm@v1.15.0/tracer.go:875 +0x6e6

[2023-10-05T14:03:25.293Z] 

[2023-10-05T14:03:25.293Z] goroutine 206 [chan send, 9 minutes]:

[2023-10-05T14:03:25.293Z] github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.TestCoordinatorShutdownErrorAllResponses(0x0?)

[2023-10-05T14:03:25.293Z] 	C:/Users/jenkins/workspace/_agent_elastic-agent-mbp_PR-3526/src/github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator/coordinator_test.go:343 +0x133

[2023-10-05T14:03:25.293Z] testing.tRunner(0xc00035c4e0, 0x15f4418)

[2023-10-05T14:03:25.293Z] 	C:/Users/jenkins/workspace/_agent_elastic-agent-mbp_PR-3526/.gvm/versions/go1.20.8.windows.amd64/src/testing/testing.go:1576 +0x217

[2023-10-05T14:03:25.293Z] created by testing.(*T).Run

[2023-10-05T14:03:25.293Z] 	C:/Users/jenkins/workspace/_agent_elastic-agent-mbp_PR-3526/.gvm/versions/go1.20.8.windows.amd64/src/testing/testing.go:1629 +0x806

[2023-10-05T14:03:25.293Z] 

[2023-10-05T14:03:25.293Z] goroutine 207 [chan send, 9 minutes]:

[2023-10-05T14:03:25.293Z] github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.setupAndWaitCoordinatorDone.func1()

[2023-10-05T14:03:25.293Z] 	C:/Users/jenkins/workspace/_agent_elastic-agent-mbp_PR-3526/src/github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator/coordinator_test.go:398 +0xab

[2023-10-05T14:03:25.293Z] created by github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.setupAndWaitCoordinatorDone

[2023-10-05T14:03:25.293Z] 	C:/Users/jenkins/workspace/_agent_elastic-agent-mbp_PR-3526/src/github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator/coordinator_test.go:396 +0x35b

[2023-10-05T14:03:25.293Z] FAIL	github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator	600.272s

[2023-10-05T14:03:25.293Z] 

[2023-10-05T14:03:25.293Z] === FAIL: internal/pkg/agent/application/coordinator TestCoordinatorShutdownErrorAllResponses (unknown)

```

**Comment by pierrehilbert** [comment]
Fixed by https://github.com/elastic/elastic-agent/pull/3549
