### ISSUE TITLE
TestManager_FakeInput_NoDeadlock is flaky

### ISSUE THREAD

**Issue by faec** [elastic/elastic-agent#3716]
## Flaky Test

* **Test Name:** `TestManager_FakeInput_NoDeadlock`
* **Link:** https://github.com/elastic/elastic-agent/blob/dba216671d99e391ca66381f251d42dd04a6afc9/pkg/component/runtime/manager_test.go#L1447
* **Branch:** main
* **Notes:** I only see this failure when running the whole `TestManager_FakeInput*` test set, running `TestManager_FakeInput_NoDeadlock` in isolation doesn't seem to trigger it, so this is probably a cleanup conflict with another test. The posted stack trace is a timeout after 2 minutes. When not setting a timeout, the test eventually cancelled itself, but instead of cleanly shutting down and reporting failure the FakeInput component started dumping hundreds of RPC errors per second to the terminal, presumably because it lost its component runtime connection.

### Stack Trace

```
=== RUN   TestManager_FakeInput_NoDeadlock
panic: test timed out after 2m0s
running tests:
	TestManager_FakeInput_NoDeadlock (1m54s)

goroutine 292 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:2241 +0x3c5
created by time.goFunc
	/usr/local/go/src/time/sleep.go:176 +0x32

goroutine 1 [chan receive, 1 minutes]:
testing.(*T).Run(0xc000602680, {0x100aa0614?, 0x66d84865aaf0?}, 0x100adb428)
	/usr/local/go/src/testing/testing.go:1630 +0x405
testing.runTests.func1(0xc00007c900?)
	/usr/local/go/src/testing/testing.go:2036 +0x45
testing.tRunner(0xc000602680, 0xc000915c88)
	/usr/local/go/src/testing/testing.go:1576 +0x10b
testing.runTests(0xc000122000?, {0x10122ebc0, 0x1f, 0x1f}, {0x7?, 0x100c000915d38?, 0x10123c5a0?})
	/usr/local/go/src/testing/testing.go:2034 +0x489
testing.(*M).Run(0xc000122000)
	/usr/local/go/src/testing/testing.go:1906 +0x63a
main.main()
	_testmain.go:107 +0x1aa

goroutine 28 [select]:
go.elastic.co/apm.(*Tracer).loop(0xc00016c000)
	/Users/fae/go/pkg/mod/go.elastic.co/apm@v1.15.0/tracer.go:975 +0xbef
created by go.elastic.co/apm.newTracer
	/Users/fae/go/pkg/mod/go.elastic.co/apm@v1.15.0/tracer.go:496 +0xae5

goroutine 239 [select, 1 minutes]:
github.com/elastic/elastic-agent/pkg/component/runtime.TestManager_FakeInput_NoDeadlock(0xc00052af50?)
	/Users/fae/go/src/github.com/elastic/elastic-agent/pkg/component/runtime/manager_test.go:1561 +0x97a
testing.tRunner(0xc0008ee820, 0x100adb428)
	/usr/local/go/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1629 +0x3ea

goroutine 39 [chan receive]:
go.elastic.co/apm.(*Tracer).loop.func2()
	/Users/fae/go/pkg/mod/go.elastic.co/apm@v1.15.0/tracer.go:878 +0x214
created by go.elastic.co/apm.(*Tracer).loop
	/Users/fae/go/pkg/mod/go.elastic.co/apm@v1.15.0/tracer.go:875 +0x3fd

goroutine 402 [syscall, 1 minutes]:
syscall.syscall6(0x10000fd88?, 0x1016055b8?, 0x17?, 0x4?, 0x0?, 0x1010000000000?, 0x10732aad8?)
	/usr/local/go/src/runtime/sys_darwin.go:45 +0x99
syscall.wait4(0xc000246f40?, 0x100010007?, 0x90?, 0x100a488a0?)
	/usr/local/go/src/syscall/zsyscall_darwin_amd64.go:43 +0x48
syscall.Wait4(0x9?, 0xc000246f74, 0xc00010e9b0?, 0x2?)
	/usr/local/go/src/syscall/syscall_bsd.go:144 +0x2b
os.(*Process).wait(0xc000954030)
	/usr/local/go/src/os/exec_unix.go:43 +0x77
os.(*Process).Wait(...)
	/usr/local/go/src/os/exec.go:132
github.com/elastic/elastic-agent/pkg/core/process.(*Info).Wait.func1()
	/Users/fae/go/src/github.com/elastic/elastic-agent/pkg/core/process/process.go:127 +0x2f
created by github.com/elastic/elastic-agent/pkg/core/process.(*Info).Wait
	/Users/fae/go/src/github.com/elastic/elastic-agent/pkg/core/process/process.go:126 +0x85

goroutine 384 [select, 1 minutes]:
google.golang.org/grpc/internal/transport.(*recvBufferReader).read(0xc00050c8c0, {0xc0005e1c30, 0x5, 0x5})
	/Users/fae/go/pkg/mod/google.golang.org/grpc@v1.58.3/internal/transport/transport.go:179 +0x90
google.golang.org/grpc/internal/transport.(*recvBufferReader).Read(0xc00050c8c0, {0xc0005e1c30?, 0xc00053a078?, 0xc00008ab40?})
	/Users/fae/go/pkg/mod/google.golang.org/grpc@v1.58.3/internal/transport/transport.go:173 +0x178
google.golang.org/grpc/internal/transport.(*transportReader).Read(0xc0005e1bc0, {0xc0005e1c30?, 0xc00008abb8?, 0x1004aa287?})
	/Users/fae/go/pkg/mod/google.golang.org/grpc@v1.58.3/internal/transport/transport.go:506 +0x32
io.ReadAtLeast({0x100bc0e20, 0xc0005e1bc0}, {0xc0005e1c30, 0x5, 0x5}, 0x5)
	/usr/local/go/src/io/io.go:332 +0x9a
io.ReadFull(...)
	/usr/local/go/src/io/io.go:351
google.golang.org/grpc/internal/transport.(*Stream).Read(0xc000486ea0, {0xc0005e1c30, 0x5, 0x5})
	/Users/fae/go/pkg/mod/google.golang.org/grpc@v1.58.3/internal/transport/transport.go:490 +0xac
google.golang.org/grpc.(*parser).recvMsg(0xc0005e1c20, 0x6400000)
	/Users/fae/go/pkg/mod/google.golang.org/grpc@v1.58.3/rpc_util.go:600 +0x55
google.golang.org/grpc.recvAndDecompress(0x10000fc2a?, 0xc000486ea0, {0x0, 0x0}, 0x6400000, 0x0, {0x0, 0x0})
	/Users/fae/go/pkg/mod/google.golang.org/grpc@v1.58.3/rpc_util.go:730 +0x66
google.golang.org/grpc.recv(0xc0005e1c20, {0x101698a48, 0x10126bbc0}, 0xc000118120?, {0x0, 0x0}, {0x100a0a5a0, 0xc00049aa80}, 0xc000666418?, 0x0, ...)
	/Users/fae/go/pkg/mod/google.golang.org/grpc@v1.58.3/rpc_util.go:796 +0xa7
google.golang.org/grpc.(*serverStream).RecvMsg(0xc0001b83c0, {0x100a0a5a0?, 0xc00049aa80})
	/Users/fae/go/pkg/mod/google.golang.org/grpc@v1.58.3/stream.go:1716 +0x178
github.com/elastic/elastic-agent-client/v7/pkg/proto.(*elasticAgentActionsServer).Recv(0xc000675ac0)
	/Users/fae/go/pkg/mod/github.com/elastic/elastic-agent-client/v7@v7.5.0/pkg/proto/elastic-agent-client_grpc.pb.go:301 +0x4c
github.com/elastic/elastic-agent/pkg/component/runtime.(*runtimeComm).actions.func3()
	/Users/fae/go/src/github.com/elastic/elastic-agent/pkg/component/runtime/runtime_comm.go:342 +0x78
created by github.com/elastic/elastic-agent/pkg/component/runtime.(*runtimeComm).actions
	/Users/fae/go/src/github.com/elastic/elastic-agent/pkg/component/runtime/runtime_comm.go:340 +0x29c

goroutine 289 [IO wait, 1 minutes]:
internal/poll.runtime_pollWait(0x129859d58, 0x72)
	/usr/local/go/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc00049a180?, 0x0?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc00049a180)
	/usr/local/go/src/internal/poll/fd_unix.go:614 +0x2bd
net.(*netFD).accept(0xc00049a180)
	/usr/local/go/src/net/fd_unix.go:172 +0x35
net.(*TCPListener).accept(0xc0006411b8)
	/usr/local/go/src/net/tcpsock_posix.go:148 +0x25
net.(*TCPListener).Accept(0xc0006411b8)
	/usr/local/go/src/net/tcpsock.go:297 +0x3d
google.golang.org/grpc.(*Server).Serve(0xc0009aa3c0, {0x100bc6dd0?, 0xc0006411b8})
	/Users/fae/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:852 +0x475
github.com/elastic/elastic-agent/pkg/component/runtime.(*Manager).Run.func1()
	/Users/fae/go/src/github.com/elastic/elastic-agent/pkg/component/runtime/manager.go:220 +0xd2
created by github.com/elastic/elastic-agent/pkg/component/runtime.(*Manager).Run
	/Users/fae/go/src/github.com/elastic/elastic-agent/pkg/component/runtime/manager.go:216 +0x7bf

goroutine 404 [select]:
github.com/elastic/elastic-agent/pkg/component/runtime.(*runtimeComm).checkin.func2()
	/Users/fae/go/src/github.com/elastic/elastic-agent/pkg/component/runtime/runtime_comm.go:235 +0x2d4
created by github.com/elastic/elastic-agent/pkg/component/runtime.(*runtimeComm).checkin
	/Users/fae/go/src/github.com/elastic/elastic-agent/pkg/component/runtime/runtime_comm.go:212 +0x24c

goroutine 333 [runnable]:
google.golang.org/grpc/internal/transport.(*controlBuffer).get(0xc00050c550, 0x1)
	/Users/fae/go/pkg/mod/google.golang.org/grpc@v1.58.3/internal/transport/controlbuf.go:418 +0x115
google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc0005f8700)
	/Users/fae/go/pkg/mod/google.golang.org/grpc@v1.58.3/internal/transport/controlbuf.go:552 +0x91
google.golang.org/grpc/internal/transport.NewServerTransport.func2()
	/Users/fae/go/pkg/mod/google.golang.org/grpc@v1.58.3/internal/transport/http2_server.go:336 +0xda
created by google.golang.org/grpc/internal/transport.NewServerTransport
	/Users/fae/go/pkg/mod/google.golang.org/grpc@v1.58.3/internal/transport/http2_server.go:333 +0x1a73

goroutine 334 [select, 1 minutes]:
google.golang.org/grpc/internal/transport.(*http2Server).keepalive(0xc0008eeb60)
	/Users/fae/go/pkg/mod/google.golang.org/grpc@v1.58.3/internal/transport/http2_server.go:1150 +0x233
created by google.golang.org/grpc/internal/transport.NewServerTransport
	/Users/fae/go/pkg/mod/google.golang.org/grpc@v1.58.3/internal/transport/http2_server.go:339 +0x1ab8

goroutine 381 [select]:
github.com/elastic/elastic-agent/pkg/component/runtime.TestManager_FakeInput_NoDeadlock.func3()
	/Users/fae/go/src/github.com/elastic/elastic-agent/pkg/component/runtime/manager_test.go:1538 +0x12e
created by github.com/elastic/elastic-agent/pkg/component/runtime.TestManager_FakeInput_NoDeadlock
	/Users/fae/go/src/github.com/elastic/elastic-agent/pkg/component/runtime/manager_test.go:1534 +0x77c

goroutine 380 [runnable]:
strings.Index({0x10093bbba, 0x12}, {0x100bb93b0, 0x1})
	/usr/local/go/src/strings/strings.go:1178 +0x694
strings.genSplit({0x10093bbba, 0x12}, {0x100bb93b0, 0x1}, 0x0, 0x0?)
	/usr/local/go/src/strings/strings.go:251 +0x11d
strings.Split(...)
	/usr/local/go/src/strings/strings.go:305
github.com/elastic/elastic-agent/pkg/component.getJSONFieldName({{0x10093bb7e, 0x8}, {0x0, 0x0}, {0x100bdcec8, 0x100912e40}, {0x10093bb87, 0x46}, 0x60, {0xc00056c660, ...}, ...})
	/Users/fae/go/src/github.com/elastic/elastic-agent/pkg/component/config.go:196 +0x57
github.com/elastic/elastic-agent/pkg/component.setSource({0x100a1f5c0, 0xc0001d5dd0}, 0xc000b4ec60?)
	/Users/fae/go/src/github.com/elastic/elastic-agent/pkg/component/config.go:131 +0x4f8
github.com/elastic/elastic-agent/pkg/component.ExpectedConfig(0x100956240?)
	/Users/fae/go/src/github.com/elastic/elastic-agent/pkg/component/config.go:99 +0xc6
github.com/elastic/elastic-agent/pkg/component.MustExpectedConfig(...)
	/Users/fae/go/src/github.com/elastic/elastic-agent/pkg/component/config.go:67
github.com/elastic/elastic-agent/pkg/component/runtime.TestManager_FakeInput_NoDeadlock.func2()
	/Users/fae/go/src/github.com/elastic/elastic-agent/pkg/component/runtime/manager_test.go:1516 +0x291
created by github.com/elastic/elastic-agent/pkg/component/runtime.TestManager_FakeInput_NoDeadlock
	/Users/fae/go/src/github.com/elastic/elastic-agent/pkg/component/runtime/manager_test.go:1502 +0x6de

goroutine 382 [select]:
github.com/elastic/elastic-agent/pkg/component/runtime.(*componentRuntimeState).runLoop(0xc0008ee4e0)
	/Users/fae/go/src/github.com/elastic/elastic-agent/pkg/component/runtime/runtime.go:142 +0x191
created by github.com/elastic/elastic-agent/pkg/component/runtime.newComponentRuntimeState
	/Users/fae/go/src/github.com/elastic/elastic-agent/pkg/component/runtime/runtime.go:128 +0x2ea

goroutine 335 [IO wait]:
internal/poll.runtime_pollWait(0x129859998, 0x72)
	/usr/local/go/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc00033a100?, 0xc00065e000?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00033a100, {0xc00065e000, 0x600, 0x600})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x299
net.(*netFD).Read(0xc00033a100, {0xc00065e000?, 0xc00065e005?, 0x72?})
	/usr/local/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc0005e6340, {0xc00065e000?, 0x0?, 0xc000209a30?})
	/usr/local/go/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc0005324e0, {0xc00065e000?, 0xc0005324e0?, 0x0?})
	/usr/local/go/src/crypto/tls/conn.go:788 +0x3d
bytes.(*Buffer).ReadFrom(0xc000209b10, {0x100bbefe0, 0xc0005324e0})
	/usr/local/go/src/bytes/buffer.go:202 +0x98
crypto/tls.(*Conn).readFromUntil(0xc000209880, {0x129e02ec0?, 0xc0005e6340}, 0x600?)
	/usr/local/go/src/crypto/tls/conn.go:810 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc000209880, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:617 +0x116
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:583
crypto/tls.(*Conn).Read(0xc000209880, {0xc000660000, 0x8000, 0x0?})
	/usr/local/go/src/crypto/tls/conn.go:1316 +0x16f
bufio.(*Reader).Read(0xc0003ea780, {0xc0001da3c0, 0x9, 0x101607b00?})
	/usr/local/go/src/bufio/bufio.go:237 +0x1bb
io.ReadAtLeast({0x100bbee00, 0xc0003ea780}, {0xc0001da3c0, 0x9, 0x9}, 0x9)
	/usr/local/go/src/io/io.go:332 +0x9a
io.ReadFull(...)
	/usr/local/go/src/io/io.go:351
golang.org/x/net/http2.readFrameHeader({0xc0001da3c0?, 0x9?, 0x0?}, {0x100bbee00?, 0xc0003ea780?})
	/Users/fae/go/pkg/mod/golang.org/x/net@v0.17.0/http2/frame.go:237 +0x6e
golang.org/x/net/http2.(*Framer).ReadFrame(0xc0001da380)
	/Users/fae/go/pkg/mod/golang.org/x/net@v0.17.0/http2/frame.go:498 +0x95
google.golang.org/grpc/internal/transport.(*http2Server).HandleStreams(0xc0008eeb60, 0x1?, 0xc0000b05a0?)
	/Users/fae/go/pkg/mod/google.golang.org/grpc@v1.58.3/internal/transport/http2_server.go:637 +0x167
google.golang.org/grpc.(*Server).serveStreams(0xc0009aa3c0, {0x100bcc458?, 0xc0008eeb60})
	/Users/fae/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:979 +0x1ec
google.golang.org/grpc.(*Server).handleRawConn.func1()
	/Users/fae/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:920 +0x46
created by google.golang.org/grpc.(*Server).handleRawConn
	/Users/fae/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:919 +0x185

goroutine 337 [chan receive, 1 minutes]:
github.com/elastic/elastic-agent/pkg/component/runtime.(*runtimeComm).actions(0xc0001da1c0, {0x100bcbe48?, 0xc000675ac0})
	/Users/fae/go/src/github.com/elastic/elastic-agent/pkg/component/runtime/runtime_comm.go:354 +0x2a8
github.com/elastic/elastic-agent/pkg/component/runtime.(*Manager).Actions(0xc0000ee000, {0x100bcbe48?, 0xc000675ac0})
	/Users/fae/go/src/github.com/elastic/elastic-agent/pkg/component/runtime/manager.go:657 +0x426
github.com/elastic/elastic-agent-client/v7/pkg/proto._ElasticAgent_Actions_Handler({0x100a43f80?, 0xc0000ee000}, {0x100bc9ca0?, 0xc0001b83c0})
	/Users/fae/go/pkg/mod/github.com/elastic/elastic-agent-client/v7@v7.5.0/pkg/proto/elastic-agent-client_grpc.pb.go:282 +0x9f
google.golang.org/grpc.(*Server).processStreamingRPC(0xc0009aa3c0, {0x100bcc458, 0xc0008eeb60}, 0xc000486ea0, 0xc000223440, 0x10122b5a0, 0x0)
	/Users/fae/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:1668 +0x1384
google.golang.org/grpc.(*Server).handleStream(0xc0009aa3c0, {0x100bcc458, 0xc0008eeb60}, 0xc000486ea0, 0x0)
	/Users/fae/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:1755 +0x9f0
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	/Users/fae/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:986 +0xca
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/Users/fae/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:997 +0x15c

goroutine 286 [chan receive, 1 minutes]:
github.com/elastic/elastic-agent/pkg/component/runtime.(*Manager).Run(0xc0000ee000, {0x100bc78a8?, 0xc00010e910})
	/Users/fae/go/src/github.com/elastic/elastic-agent/pkg/component/runtime/manager.go:231 +0x7dc
github.com/elastic/elastic-agent/pkg/component/runtime.TestManager_FakeInput_NoDeadlock.func1()
	/Users/fae/go/src/github.com/elastic/elastic-agent/pkg/component/runtime/manager_test.go:1462 +0x2e
created by github.com/elastic/elastic-agent/pkg/component/runtime.TestManager_FakeInput_NoDeadlock
	/Users/fae/go/src/github.com/elastic/elastic-agent/pkg/component/runtime/manager_test.go:1461 +0x250

goroutine 336 [chan receive, 1 minutes]:
github.com/elastic/elastic-agent/pkg/component/runtime.(*runtimeComm).checkin(0xc0001da1c0, {0x100bcbef8?, 0xc000618210}, 0xc0000dce00)
	/Users/fae/go/src/github.com/elastic/elastic-agent/pkg/component/runtime/runtime_comm.go:285 +0x3b9
github.com/elastic/elastic-agent/pkg/component/runtime.(*Manager).CheckinV2(0xc000a13b18?, {0x100bcbef8?, 0xc000618210})
	/Users/fae/go/src/github.com/elastic/elastic-agent/pkg/component/runtime/manager.go:610 +0x267
github.com/elastic/elastic-agent-client/v7/pkg/proto._ElasticAgent_CheckinV2_Handler({0x100a43f80?, 0xc0000ee000}, {0x100bc9ca0?, 0xc00099c000})
	/Users/fae/go/pkg/mod/github.com/elastic/elastic-agent-client/v7@v7.5.0/pkg/proto/elastic-agent-client_grpc.pb.go:256 +0x9f
google.golang.org/grpc.(*Server).processStreamingRPC(0xc0009aa3c0, {0x100bcc458, 0xc0008eeb60}, 0xc000486d80, 0xc000223440, 0x10122b580, 0x0)
	/Users/fae/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:1668 +0x1384
google.golang.org/grpc.(*Server).handleStream(0xc0009aa3c0, {0x100bcc458, 0xc0008eeb60}, 0xc000486d80, 0x0)
	/Users/fae/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:1755 +0x9f0
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	/Users/fae/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:986 +0xca
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/Users/fae/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:997 +0x15c

goroutine 405 [runnable]:
google.golang.org/grpc/internal/transport.(*recvBufferReader).read(0xc00050c7d0, {0xc0003e7f60, 0x5, 0x5})
	/Users/fae/go/pkg/mod/google.golang.org/grpc@v1.58.3/internal/transport/transport.go:179 +0x90
google.golang.org/grpc/internal/transport.(*recvBufferReader).Read(0xc00050c7d0, {0xc0003e7f60?, 0xc00053a060?, 0xc000c0fb40?})
	/Users/fae/go/pkg/mod/google.golang.org/grpc@v1.58.3/internal/transport/transport.go:173 +0x178
google.golang.org/grpc/internal/transport.(*transportReader).Read(0xc0005e1aa0, {0xc0003e7f60?, 0xc000c0fbb8?, 0x1004aa287?})
	/Users/fae/go/pkg/mod/google.golang.org/grpc@v1.58.3/internal/transport/transport.go:506 +0x32
io.ReadAtLeast({0x100bc0e20, 0xc0005e1aa0}, {0xc0003e7f60, 0x5, 0x5}, 0x5)
	/usr/local/go/src/io/io.go:332 +0x9a
io.ReadFull(...)
	/usr/local/go/src/io/io.go:351
google.golang.org/grpc/internal/transport.(*Stream).Read(0xc000486d80, {0xc0003e7f60, 0x5, 0x5})
	/Users/fae/go/pkg/mod/google.golang.org/grpc@v1.58.3/internal/transport/transport.go:490 +0xac
google.golang.org/grpc.(*parser).recvMsg(0xc0003e7f50, 0x6400000)
	/Users/fae/go/pkg/mod/google.golang.org/grpc@v1.58.3/rpc_util.go:600 +0x55
google.golang.org/grpc.recvAndDecompress(0x1?, 0xc000486d80, {0x0, 0x0}, 0x6400000, 0x0, {0x0, 0x0})
	/Users/fae/go/pkg/mod/google.golang.org/grpc@v1.58.3/rpc_util.go:730 +0x66
google.golang.org/grpc.recv(0xc0003e7f50, {0x101698a48, 0x10126bbc0}, 0x5?, {0x0, 0x0}, {0x100a0a6a0, 0xc0004dab60}, 0xc000058000?, 0x0, ...)
	/Users/fae/go/pkg/mod/google.golang.org/grpc@v1.58.3/rpc_util.go:796 +0xa7
google.golang.org/grpc.(*serverStream).RecvMsg(0xc00099c000, {0x100a0a6a0?, 0xc0004dab60})
	/Users/fae/go/pkg/mod/google.golang.org/grpc@v1.58.3/stream.go:1716 +0x178
github.com/elastic/elastic-agent-client/v7/pkg/proto.(*elasticAgentCheckinV2Server).Recv(0xc000618210)
	/Users/fae/go/pkg/mod/github.com/elastic/elastic-agent-client/v7@v7.5.0/pkg/proto/elastic-agent-client_grpc.pb.go:275 +0x4c
github.com/elastic/elastic-agent/pkg/component/runtime.(*runtimeComm).checkin.func3()
	/Users/fae/go/src/github.com/elastic/elastic-agent/pkg/component/runtime/runtime_comm.go:273 +0x78
created by github.com/elastic/elastic-agent/pkg/component/runtime.(*runtimeComm).checkin
	/Users/fae/go/src/github.com/elastic/elastic-agent/pkg/component/runtime/runtime_comm.go:271 +0x3ad

goroutine 386 [select]:
github.com/elastic/elastic-agent/pkg/component/runtime.(*commandRuntime).Run(0xc0008ee340, {0x100bc78a8, 0xc0004b6000}, {0x100bc60e0, 0xc0001da1c0})
	/Users/fae/go/src/github.com/elastic/elastic-agent/pkg/component/runtime/command.go:147 +0x2a7
github.com/elastic/elastic-agent/pkg/component/runtime.(*componentRuntimeState).runLoop.func1({0x100bc78a8?, 0xc0004b6000?})
	/Users/fae/go/src/github.com/elastic/elastic-agent/pkg/component/runtime/runtime.go:137 +0x90
github.com/elastic/elastic-agent/internal/pkg/runner.Start.func1()
	/Users/fae/go/src/github.com/elastic/elastic-agent/internal/pkg/runner/runner.go:69 +0x37
created by github.com/elastic/elastic-agent/internal/pkg/runner.Start
	/Users/fae/go/src/github.com/elastic/elastic-agent/internal/pkg/runner/runner.go:68 +0x14a

goroutine 387 [IO wait, 1 minutes]:
internal/poll.runtime_pollWait(0x1298598a8, 0x72)
	/usr/local/go/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc00049cb40?, 0xc000234000?, 0x1)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00049cb40, {0xc000234000, 0x8000, 0x8000})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x299
os.(*File).read(...)
	/usr/local/go/src/os/file_posix.go:31
os.(*File).Read(0xc000636010, {0xc000234000?, 0xc000123180?, 0x0?})
	/usr/local/go/src/os/file.go:118 +0x5e
io.copyBuffer({0x100bbf980, 0xc000123180}, {0x100bc18a0, 0xc000636010}, {0x0, 0x0, 0x0})
	/usr/local/go/src/io/io.go:427 +0x1b2
io.Copy(...)
	/usr/local/go/src/io/io.go:386
os/exec.(*Cmd).writerDescriptor.func1()
	/usr/local/go/src/os/exec/exec.go:560 +0x3a
os/exec.(*Cmd).Start.func2(0xc000618020?)
	/usr/local/go/src/os/exec/exec.go:717 +0x32
created by os/exec.(*Cmd).Start
	/usr/local/go/src/os/exec/exec.go:716 +0xa33

goroutine 388 [IO wait]:
internal/poll.runtime_pollWait(0x1298597b8, 0x72)
	/usr/local/go/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc00049cc60?, 0xc00023e000?, 0x1)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00049cc60, {0xc00023e000, 0x8000, 0x8000})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x299
os.(*File).read(...)
	/usr/local/go/src/os/file_posix.go:31
os.(*File).Read(0xc000636028, {0xc00023e000?, 0x102?, 0x8000?})
	/usr/local/go/src/os/file.go:118 +0x5e
io.copyBuffer({0x100bbf980, 0xc0001234a0}, {0x100bc18a0, 0xc000636028}, {0x0, 0x0, 0x0})
	/usr/local/go/src/io/io.go:427 +0x1b2
io.Copy(...)
	/usr/local/go/src/io/io.go:386
os/exec.(*Cmd).writerDescriptor.func1()
	/usr/local/go/src/os/exec/exec.go:560 +0x3a
os/exec.(*Cmd).Start.func2(0x0?)
	/usr/local/go/src/os/exec/exec.go:717 +0x32
created by os/exec.(*Cmd).Start
	/usr/local/go/src/os/exec/exec.go:716 +0xa33

goroutine 389 [chan receive, 1 minutes]:
github.com/elastic/elastic-agent/pkg/component/runtime.(*commandRuntime).startWatcher.func1()
	/Users/fae/go/src/github.com/elastic/elastic-agent/pkg/component/runtime/command.go:433 +0x19e
created by github.com/elastic/elastic-agent/pkg/component/runtime.(*commandRuntime).startWatcher
	/Users/fae/go/src/github.com/elastic/elastic-agent/pkg/component/runtime/command.go:422 +0xaa

goroutine 383 [select, 1 minutes]:
github.com/elastic/elastic-agent/pkg/component/runtime.(*runtimeComm).actions.func2()
	/Users/fae/go/src/github.com/elastic/elastic-agent/pkg/component/runtime/runtime_comm.go:322 +0x13d
created by github.com/elastic/elastic-agent/pkg/component/runtime.(*runtimeComm).actions
	/Users/fae/go/src/github.com/elastic/elastic-agent/pkg/component/runtime/runtime_comm.go:316 +0x218
FAIL	github.com/elastic/elastic-agent/pkg/component/runtime	120.497s
FAIL
```

**Comment by cmacknz** [comment]
Another recent failure: https://github.com/elastic/elastic-agent/issues/3891
