### ISSUE TITLE
[Flaky test] TestCheckPlatformCompat

### ISSUE THREAD

**Issue by AndersonQ** [elastic/elastic-agent#3964]
## Flaky Test

* Test Name: **TestCheckPlatformCompat**
* Link: [internal/pkg/agent/cmd/platformcheck_test.go](https://github.com/elastic/elastic-agent/blob/938f0b93fe9316ee59d428c6424bf275516a8ddb/internal/pkg/agent/cmd/platformcheck_test.go#L17)
* Branch: main
* Artifact Link: [buildkite build](https://buildkite.com/elastic/elastic-agent/builds/5796#018cb084-174c-4ce7-b8f9-4cdaa1ae83ef)
* Notes: 
   - the test does not seem to have an assertion or failure condition. It seems it was made to be manually run, I'm not sure the intention of this test.
   - It seems to need to compile the test binary to force/set `GOARCH=386`.
   - the test gets stuck on `internal/pkg/agent/cmd/platformcheck_test.go:31`, which is the call to run the compiled test binary. I can only guess the test binary hangs on the syscall it uses to check the architecture. But I'm not sure.

### Stack Trace

```
=== Failed
=== FAIL: internal/pkg/agent/cmd  (0.00s)
panic: test timed out after 10m0s
running tests:
	TestCheckPlatformCompat (9m45s)
goroutine 348 [running]:
testing.(*M).startAlarm.func1()
	C:/Users/buildkite/.gvm/versions/go1.20.12.windows.amd64/src/testing/testing.go:2241 +0x219
created by time.goFunc
	C:/Users/buildkite/.gvm/versions/go1.20.12.windows.amd64/src/time/sleep.go:176 +0x48
goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc00007dd40, {0x38969f8, 0x17}, 0x3992030)
	C:/Users/buildkite/.gvm/versions/go1.20.12.windows.amd64/src/testing/testing.go:1630 +0x82e
testing.runTests.func1(0x0?)
	C:/Users/buildkite/.gvm/versions/go1.20.12.windows.amd64/src/testing/testing.go:2036 +0x8e
testing.tRunner(0xc00007dd40, 0xc0009bfb40)
	C:/Users/buildkite/.gvm/versions/go1.20.12.windows.amd64/src/testing/testing.go:1576 +0x217
testing.runTests(0xc000326be0?, {0x5299ce0, 0x18, 0x18}, {0x1c?, 0x4b38f9?, 0x52d9ca0?})
	C:/Users/buildkite/.gvm/versions/go1.20.12.windows.amd64/src/testing/testing.go:2034 +0x87d
testing.(*M).Run(0xc000326be0)
	C:/Users/buildkite/.gvm/versions/go1.20.12.windows.amd64/src/testing/testing.go:1906 +0xb45
main.main()
	_testmain.go:124 +0x2fd
goroutine 6 [select]:
go.elastic.co/apm.(*Tracer).loop(0xc000290640)
	C:/Users/buildkite/go/pkg/mod/go.elastic.co/apm@v1.15.0/tracer.go:975 +0x1576
created by go.elastic.co/apm.newTracer
	C:/Users/buildkite/go/pkg/mod/go.elastic.co/apm@v1.15.0/tracer.go:496 +0x1645
goroutine 18 [select]:
go.elastic.co/apm.(*Tracer).loop.func2()
	C:/Users/buildkite/go/pkg/mod/go.elastic.co/apm@v1.15.0/tracer.go:880 +0x3cc
created by go.elastic.co/apm.(*Tracer).loop
	C:/Users/buildkite/go/pkg/mod/go.elastic.co/apm@v1.15.0/tracer.go:875 +0x6e6
goroutine 8 [select, 5 minutes]:
go.elastic.co/apm/transport.(*HTTPTransport).WatchConfig.func1()
	C:/Users/buildkite/go/pkg/mod/go.elastic.co/apm@v1.15.0/transport/http.go:398 +0x273
created by go.elastic.co/apm/transport.(*HTTPTransport).WatchConfig
	C:/Users/buildkite/go/pkg/mod/go.elastic.co/apm@v1.15.0/transport/http.go:390 +0x1ba
goroutine 21 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000150100)
	C:/Users/buildkite/go/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:292 +0x185
created by go.opencensus.io/stats/view.init.0
	C:/Users/buildkite/go/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:34 +0x105
goroutine 200 [syscall, 9 minutes, locked to thread]:
syscall.SyscallN(0x7fffefda2e40?, {0xc000b7ba28?, 0x3?, 0x0?})
	C:/Users/buildkite/.gvm/versions/go1.20.12.windows.amd64/src/runtime/syscall_windows.go:557 +0x109
syscall.Syscall(0xc000067620?, 0x90?, 0x90?, 0x3?, 0x3?)
	C:/Users/buildkite/.gvm/versions/go1.20.12.windows.amd64/src/runtime/syscall_windows.go:495 +0x3b
syscall.WaitForSingleObject(0x0?, 0xffffffff)
	C:/Users/buildkite/.gvm/versions/go1.20.12.windows.amd64/src/syscall/zsyscall_windows.go:1145 +0xa8
os.(*Process).wait(0xc00080b410)
	C:/Users/buildkite/.gvm/versions/go1.20.12.windows.amd64/src/os/exec_windows.go:18 +0x78
os.(*Process).Wait(...)
	C:/Users/buildkite/.gvm/versions/go1.20.12.windows.amd64/src/os/exec.go:132
os/exec.(*Cmd).Wait(0xc000812000)
	C:/Users/buildkite/.gvm/versions/go1.20.12.windows.amd64/src/os/exec/exec.go:890 +0xc5
os/exec.(*Cmd).Run(0x386c04a?)
	C:/Users/buildkite/.gvm/versions/go1.20.12.windows.amd64/src/os/exec/exec.go:590 +0x65
github.com/elastic/elastic-agent/internal/pkg/agent/cmd.TestCheckPlatformCompat(0xc000b90ea0)
	C:/buildkite-agent/builds/bk-agent-prod-gcp-1703768502685071137/elastic/elastic-agent/internal/pkg/agent/cmd/platformcheck_test.go:31 +0x38a
testing.tRunner(0xc000b90ea0, 0x3992030)
	C:/Users/buildkite/.gvm/versions/go1.20.12.windows.amd64/src/testing/testing.go:1576 +0x217
created by testing.(*T).Run
	C:/Users/buildkite/.gvm/versions/go1.20.12.windows.amd64/src/testing/testing.go:1629 +0x806
goroutine 179 [select, 9 minutes]:
io.(*pipe).read(0xc000b8f4a0, {0xc000a681c2, 0xe3e, 0xc00095b270?})
	C:/Users/buildkite/.gvm/versions/go1.20.12.windows.amd64/src/io/pipe.go:57 +0x151
io.(*PipeReader).Read(0xc000664848, {0xc000a681c2, 0xe3e, 0xe3e})
	C:/Users/buildkite/.gvm/versions/go1.20.12.windows.amd64/src/io/pipe.go:136 +0x65
bufio.(*Scanner).Scan(0xc00091cd80)
	C:/Users/buildkite/.gvm/versions/go1.20.12.windows.amd64/src/bufio/scan.go:214 +0x13d6
github.com/elastic/elastic-agent/internal/pkg/agent/cmd.newWrappedWriter.func1()
	C:/buildkite-agent/builds/bk-agent-prod-gcp-1703768502685071137/elastic/elastic-agent/internal/pkg/agent/cmd/logs.go:142 +0x90
created by github.com/elastic/elastic-agent/internal/pkg/agent/cmd.newWrappedWriter
	C:/buildkite-agent/builds/bk-agent-prod-gcp-1703768502685071137/elastic/elastic-agent/internal/pkg/agent/cmd/logs.go:141 +0x50a
*** Test killed: ran too long (11m0s).
FAIL	github.com/elastic/elastic-agent/internal/pkg/agent/cmd	737.140s
=== FAIL: internal/pkg/agent/cmd TestCheckPlatformCompat (unknown)
	github.com/elastic/elastic-agent/internal/pkg/agent/cmd	coverage: 19.3% of statements
DONE 1725 tests, 19 skipped, 2 failures in 1678.813s
Error: go test returned a non-zero value: exit status 1
```

**Comment by macdewee** [comment]
Test removed in https://github.com/elastic/elastic-agent/pull/5371
