### ISSUE TITLE
[Flaky Test]: TestManager_StartStopComponent – panic: test timed out after 10m0s

### ISSUE THREAD

**Issue by rdner** [elastic/elastic-agent#4502]
### Failing test case

TestManager_StartStopComponent

### Error message

panic: test timed out after 10m0s

### Build

https://buildkite.com/elastic/elastic-agent/builds/8017#018e8b05-4f91-450f-9c87-df9f94ba7f52

### OS

Mac

### Stacktrace and notes

```markdown
=== Failed
=== FAIL: pkg/component/runtime  (0.00s)
panic: test timed out after 10m0s
running tests:
	TestFakeInputSuite (9m57s)
	TestFakeInputSuite/TestManager_StartStopComponent (6m20s)
goroutine 640896 [running]:
testing.(*M).startAlarm.func1()
	/Users/admin/.gvm/versions/go1.21.8.darwin.amd64/src/testing/testing.go:2259 +0x259
created by time.goFunc
	/Users/admin/.gvm/versions/go1.21.8.darwin.amd64/src/time/sleep.go:176 +0x45
goroutine 1 [chan receive, 10 minutes]:
testing.(*T).Run(0xc000092b60, {0x10119bfab, 0x12}, 0x1011e6b18)
	/Users/admin/.gvm/versions/go1.21.8.darwin.amd64/src/testing/testing.go:1649 +0x871
testing.runTests.func1(0x0?)
	/Users/admin/.gvm/versions/go1.21.8.darwin.amd64/src/testing/testing.go:2054 +0x85
testing.tRunner(0xc000092b60, 0xc000797ae8)
	/Users/admin/.gvm/versions/go1.21.8.darwin.amd64/src/testing/testing.go:1595 +0x262
testing.runTests(0xc0002cc140?, {0x101ac2060, 0xe, 0xe}, {0x1000151f5?, 0xd0?, 0x101ad6740?})
	/Users/admin/.gvm/versions/go1.21.8.darwin.amd64/src/testing/testing.go:2052 +0x8ae
testing.(*M).Run(0xc0002cc140)
	/Users/admin/.gvm/versions/go1.21.8.darwin.amd64/src/testing/testing.go:1925 +0xcd8
main.main()
	_testmain.go:107 +0x2e5
goroutine 9 [select]:
go.elastic.co/apm.(*Tracer).loop(0xc0002f8640)
	/Users/admin/go/pkg/mod/go.elastic.co/apm@v1.15.0/tracer.go:975 +0x15d6
created by go.elastic.co/apm.newTracer in goroutine 1
	/Users/admin/go/pkg/mod/go.elastic.co/apm@v1.15.0/tracer.go:496 +0x1c71
goroutine 20 [select]:
go.elastic.co/apm/transport/transporttest.ErrorTransport.SendStream({{0x0?, 0x0?}}, {0x101351388, 0xc00007eaf0}, {0x10134a080?, 0xc0073a20c0})
	/Users/admin/go/pkg/mod/go.elastic.co/apm@v1.15.0/transport/transporttest/err.go:45 +0x1cc
go.elastic.co/apm.(*Tracer).loop.func2()
	/Users/admin/go/pkg/mod/go.elastic.co/apm@v1.15.0/tracer.go:885 +0x338
created by go.elastic.co/apm.(*Tracer).loop in goroutine 9
	/Users/admin/go/pkg/mod/go.elastic.co/apm@v1.15.0/tracer.go:875 +0x72b
goroutine 81 [chan receive, 6 minutes]:
testing.(*T).Run(0xc000350d00, {0x100fb8702, 0x1e}, 0xc0003550e0)
	/Users/admin/.gvm/versions/go1.21.8.darwin.amd64/src/testing/testing.go:1649 +0x871
github.com/stretchr/testify/suite.runTests({0x10135b6e0, 0xc000350d00}, {0xc000336300?, 0x14, 0x20})
	/Users/admin/go/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:242 +0x187
github.com/stretchr/testify/suite.Run(0xc000350d00, {0x10134f418?, 0xc0007c8bc0})
	/Users/admin/go/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:215 +0xa4f
github.com/elastic/elastic-agent/pkg/component/runtime.TestFakeInputSuite(0x0?)
	/Users/admin/builds/bk-agent-prod-orka-1711729368121929133/elastic/elastic-agent/pkg/component/runtime/manager_fake_input_test.go:90 +0x3d
testing.tRunner(0xc000350d00, 0x1011e6b18)
	/Users/admin/.gvm/versions/go1.21.8.darwin.amd64/src/testing/testing.go:1595 +0x262
created by testing.(*T).Run in goroutine 1
	/Users/admin/.gvm/versions/go1.21.8.darwin.amd64/src/testing/testing.go:1648 +0x846
goroutine 640815 [chan receive, 6 minutes]:
github.com/elastic/elastic-agent/pkg/component/runtime.(*FakeInputSuite).TestManager_StartStopComponent(0xc0007c8bc0)
	/Users/admin/builds/bk-agent-prod-orka-1711729368121929133/elastic/elastic-agent/pkg/component/runtime/manager_fake_input_test.go:3194 +0x20aa
reflect.Value.call({0xc0007c9d00?, 0xc0002d14b8?, 0x13?}, {0x10118ecc3, 0x4}, {0xc000909db0, 0x1, 0x1?})
	/Users/admin/.gvm/versions/go1.21.8.darwin.amd64/src/reflect/value.go:596 +0x14ce
reflect.Value.Call({0xc0007c9d00?, 0xc0002d14b8?, 0xc0007c8bc0?}, {0xc002856db0, 0x1, 0x1})
	/Users/admin/.gvm/versions/go1.21.8.darwin.amd64/src/reflect/value.go:380 +0xb6
github.com/stretchr/testify/suite.Run.func1(0xc000482820)
	/Users/admin/go/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:197 +0x767
testing.tRunner(0xc000482820, 0xc0003550e0)
	/Users/admin/.gvm/versions/go1.21.8.darwin.amd64/src/testing/testing.go:1595 +0x262
created by testing.(*T).Run in goroutine 81
	/Users/admin/.gvm/versions/go1.21.8.darwin.amd64/src/testing/testing.go:1648 +0x846
goroutine 640897 [chan receive]:
go.elastic.co/apm/internal/iochan.(*Reader).Read(0xc0073a20c0, {0xc000186000, 0x2000, 0x2000})
	/Users/admin/go/pkg/mod/go.elastic.co/apm@v1.15.0/internal/iochan/reader.go:87 +0x1c5
io.discard.ReadFrom({}, {0x10134a080, 0xc0073a20c0})
	/Users/admin/.gvm/versions/go1.21.8.darwin.amd64/src/io/io.go:658 +0x92
io.copyBuffer({0x101348520, 0x102a4bfc0}, {0x10134a080, 0xc0073a20c0}, {0x0, 0x0, 0x0})
	/Users/admin/.gvm/versions/go1.21.8.darwin.amd64/src/io/io.go:416 +0x1bf
io.Copy(...)
	/Users/admin/.gvm/versions/go1.21.8.darwin.amd64/src/io/io.go:389
go.elastic.co/apm/transport/transporttest.ErrorTransport.SendStream.func1()
	/Users/admin/go/pkg/mod/go.elastic.co/apm@v1.15.0/transport/transporttest/err.go:42 +0x70
created by go.elastic.co/apm/transport/transporttest.ErrorTransport.SendStream in goroutine 20
	/Users/admin/go/pkg/mod/go.elastic.co/apm@v1.15.0/transport/transporttest/err.go:41 +0x134
goroutine 640711 [chan send, 6 minutes]:
github.com/elastic/elastic-agent/pkg/component/runtime.(*FakeInputSuite).TestManager_Shipper.func2()
	/Users/admin/builds/bk-agent-prod-orka-1711729368121929133/elastic/elastic-agent/pkg/component/runtime/manager_fake_input_test.go:2936 +0xd3d
created by github.com/elastic/elastic-agent/pkg/component/runtime.(*FakeInputSuite).TestManager_Shipper in goroutine 640698
	/Users/admin/builds/bk-agent-prod-orka-1711729368121929133/elastic/elastic-agent/pkg/component/runtime/manager_fake_input_test.go:2824 +0x160b
goroutine 640831 [select, 6 minutes]:
github.com/elastic/elastic-agent/pkg/component/runtime.(*componentRuntimeState).runLoop(0xc0004829c0)
	/Users/admin/builds/bk-agent-prod-orka-1711729368121929133/elastic/elastic-agent/pkg/component/runtime/runtime.go:142 +0x2e9
created by github.com/elastic/elastic-agent/pkg/component/runtime.newComponentRuntimeState in goroutine 640862
	/Users/admin/builds/bk-agent-prod-orka-1711729368121929133/elastic/elastic-agent/pkg/component/runtime/runtime.go:128 +0x614
goroutine 640866 [chan send, 6 minutes]:
github.com/elastic/elastic-agent/pkg/component/runtime.(*commandRuntime).startWatcher.func1()
	/Users/admin/builds/bk-agent-prod-orka-1711729368121929133/elastic/elastic-agent/pkg/component/runtime/command.go:434 +0x32c
created by github.com/elastic/elastic-agent/pkg/component/runtime.(*commandRuntime).startWatcher in goroutine 640849
	/Users/admin/builds/bk-agent-prod-orka-1711729368121929133/elastic/elastic-agent/pkg/component/runtime/command.go:422 +0x165
goroutine 640849 [chan send, 6 minutes]:
github.com/elastic/elastic-agent/pkg/component/runtime.(*runtimeComm).CheckinExpected(0xc0004ec000, 0xc0004eabd0, 0xc00a78cd80)
	/Users/admin/builds/bk-agent-prod-orka-1711729368121929133/elastic/elastic-agent/pkg/component/runtime/runtime_comm.go:180 +0x485
github.com/elastic/elastic-agent/pkg/component/runtime.(*commandRuntime).Run(0xc000482680, {0x101351388, 0xc001c30460}, {0x10134f478, 0xc0004ec000})
	/Users/admin/builds/bk-agent-prod-orka-1711729368121929133/elastic/elastic-agent/pkg/component/runtime/command.go:207 +0x1d6b
github.com/elastic/elastic-agent/pkg/component/runtime.(*componentRuntimeState).runLoop.func1({0x101351388, 0xc001c30460})
	/Users/admin/builds/bk-agent-prod-orka-1711729368121929133/elastic/elastic-agent/pkg/component/runtime/runtime.go:137 +0x14a
github.com/elastic/elastic-agent/internal/pkg/runner.Start.func1()
	/Users/admin/builds/bk-agent-prod-orka-1711729368121929133/elastic/elastic-agent/internal/pkg/runner/runner.go:69 +0x5d
created by github.com/elastic/elastic-agent/internal/pkg/runner.Start in goroutine 640831
	/Users/admin/builds/bk-agent-prod-orka-1711729368121929133/elastic/elastic-agent/internal/pkg/runner/runner.go:68 +0x288
goroutine 640834 [chan receive]:
github.com/elastic/elastic-agent/pkg/component/runtime.(*Manager).shutdown(0xc0052f67e0)
	/Users/admin/builds/bk-agent-prod-orka-1711729368121929133/elastic/elastic-agent/pkg/component/runtime/manager.go:872 +0xc5
github.com/elastic/elastic-agent/pkg/component/runtime.(*Manager).Run(0xc0052f67e0, {0x101351388?, 0xc001c30050})
	/Users/admin/builds/bk-agent-prod-orka-1711729368121929133/elastic/elastic-agent/pkg/component/runtime/manager.go:242 +0xff3
github.com/elastic/elastic-agent/pkg/component/runtime.(*FakeInputSuite).TestManager_StartStopComponent.func1()
	/Users/admin/builds/bk-agent-prod-orka-1711729368121929133/elastic/elastic-agent/pkg/component/runtime/manager_fake_input_test.go:3038 +0xcb
created by github.com/elastic/elastic-agent/pkg/component/runtime.(*FakeInputSuite).TestManager_StartStopComponent in goroutine 640815
	/Users/admin/builds/bk-agent-prod-orka-1711729368121929133/elastic/elastic-agent/pkg/component/runtime/manager_fake_input_test.go:3036 +0x3da
goroutine 640823 [IO wait, 6 minutes]:
internal/poll.runtime_pollWait(0x14b588468, 0x72)
	/Users/admin/.gvm/versions/go1.21.8.darwin.amd64/src/runtime/netpoll.go:343 +0x85
internal/poll.(*pollDesc).wait(0xc00026aca0, 0x10007a801?, 0x0)
	/Users/admin/.gvm/versions/go1.21.8.darwin.amd64/src/internal/poll/fd_poll_runtime.go:84 +0xb1
internal/poll.(*pollDesc).waitRead(...)
	/Users/admin/.gvm/versions/go1.21.8.darwin.amd64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc00026ac80)
	/Users/admin/.gvm/versions/go1.21.8.darwin.amd64/src/internal/poll/fd_unix.go:611 +0x425
net.(*netFD).accept(0xc00026ac80)
	/Users/admin/.gvm/versions/go1.21.8.darwin.amd64/src/net/fd_unix.go:172 +0x3e
net.(*TCPListener).accept(0xc0002ce5e0)
	/Users/admin/.gvm/versions/go1.21.8.darwin.amd64/src/net/tcpsock_posix.go:152 +0x3e
net.(*TCPListener).Accept(0xc0002ce5e0)
	/Users/admin/.gvm/versions/go1.21.8.darwin.amd64/src/net/tcpsock.go:315 +0x65
google.golang.org/grpc.(*Server).Serve(0xc0001f6400, {0x10134f7a8, 0xc0002ce5e0})
	/Users/admin/go/pkg/mod/google.golang.org/grpc@v1.62.0/server.go:883 +0x611
github.com/elastic/elastic-agent/pkg/component/runtime.(*Manager).serverLoop(0xc0052f67e0, {0x101351388, 0xc001c30050}, {0x10134f7a8, 0xc0002ce5e0}, 0xc000974330?)
	/Users/admin/builds/bk-agent-prod-orka-1711729368121929133/elastic/elastic-agent/pkg/component/runtime/manager.go:316 +0x114
github.com/elastic/elastic-agent/pkg/component/runtime.(*Manager).Run.func1()
	/Users/admin/builds/bk-agent-prod-orka-1711729368121929133/elastic/elastic-agent/pkg/component/runtime/manager.go:234 +0x113
created by github.com/elastic/elastic-agent/pkg/component/runtime.(*Manager).Run in goroutine 640834
	/Users/admin/builds/bk-agent-prod-orka-1711729368121929133/elastic/elastic-agent/pkg/component/runtime/manager.go:232 +0xfb8
FAIL	github.com/elastic/elastic-agent/pkg/component/runtime	601.130s
=== FAIL: pkg/component/runtime TestFakeInputSuite (unknown)
{"log.level":"info","@timestamp":"2024-03-29T09:36:23.225-0700","log.origin":{"file.name":"runtime/manager.go","file.line":213},"message":"Starting grpc control protocol listener on port 6789 with max_message_size 104857600","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2024-03-29T09:36:23.757-0700","log.origin":{"file.name":"runtime/manager.go","file.line":806},"message":"Starting component \"fake-default\"","ecs.version":"1.6.0"}
    manager_fake_input_test.go:408: component state changed: {State:STARTING Message:Starting: spawned pid '7649' Units:map[{UnitType:input UnitID:fake-input}:{State:STARTING Message:Starting: spawned pid '7649' Payload:map[] unitState:0 unitMessage:Starting unitPayload:map[] configStateIdx:0 err:<nil>}] Features:<nil> FeaturesIdx:0 Component:<nil> ComponentIdx:0 VersionInfo:{Name: Meta:map[] BuildHash:} expectedUnits:map[{UnitType:0 UnitID:fake-input}:{state:2 configStateIdx:1 config:0xc00079a090 err:<nil> logLevel:4}] expectedFeatures:<nil> expectedFeaturesIdx:1 expectedComponent:<nil> expectedComponentIdx:1}
{"log.level":"info","@timestamp":"2024-03-29T09:36:23.980-0700","log.logger":"component.runtime.fake-default","log.origin":{"file.name":"runtime/manager.go","file.line":680},"message":"control checkin v2 protocol has chunking enabled","ecs.version":"1.6.0"}
    manager_fake_input_test.go:408: component state changed: {State:HEALTHY Message:Healthy: communicating with pid '7649' Units:map[{UnitType:input UnitID:fake-input}:{State:STARTING Message:Starting: spawned pid '7649' Payload:map[] unitState:0 unitMessage: unitPayload:map[] configStateIdx:0 err:<nil>}] Features:<nil> FeaturesIdx:0 Component:<nil> ComponentIdx:0 VersionInfo:{Name:fake Meta:map[input:fake] BuildHash:} expectedUnits:map[{UnitType:0 UnitID:fake-input}:{state:2 configStateIdx:1 config:0xc00079a090 err:<nil> logLevel:4}] expectedFeatures:<nil> expectedFeaturesIdx:1 expectedComponent:<nil> expectedComponentIdx:1}
{"log.level":"info","@timestamp":"0000-01-01T00:00:00.000Z","message":"","component":{"binary":"","dataset":"elastic_agent.","id":"fake-default","type":"fake"},"log":{"source":"fake-default"},"level":"info","state":"STARTING","expectedState":"HEALTHY","time":"2024-03-29T09:36:23-07:00","message":"unit change received","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"0000-01-01T00:00:00.000Z","message":"","component":{"binary":"","dataset":"elastic_agent.","id":"fake-default","type":"fake"},"log":{"source":"fake-default"},"level":"trace","time":"2024-03-29T09:36:23-07:00","message":"registering set_state action for unit","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"0000-01-01T00:00:00.000Z","message":"","component":{"binary":"","dataset":"elastic_agent.","id":"fake-default","type":"fake"},"log":{"source":"fake-default"},"level":"trace","time":"2024-03-29T09:36:23-07:00","message":"registering send_event action for unit","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"0000-01-01T00:00:00.000Z","message":"","component":{"binary":"","dataset":"elastic_agent.","id":"fake-default","type":"fake"},"log":{"source":"fake-default"},"level":"trace","time":"2024-03-29T09:36:23-07:00","message":"registering kill action for unit","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"0000-01-01T00:00:00.000Z","message":"","component":{"binary":"","dataset":"elastic_agent.","id":"fake-default","type":"fake"},"log":{"source":"fake-default"},"level":"trace","time":"2024-03-29T09:36:23-07:00","message":"registering retrieve_features action for unit","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"0000-01-01T00:00:00.000Z","message":"","component":{"binary":"","dataset":"elastic_agent.","id":"fake-default","type":"fake"},"log":{"source":"fake-default"},"level":"trace","time":"2024-03-29T09:36:23-07:00","message":"registering retrieve_apm_config action for unit","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"0000-01-01T00:00:00.000Z","message":"","component":{"binary":"","dataset":"elastic_agent.","id":"fake-default","type":"fake"},"log":{"source":"fake-default"},"time":"2024-03-29T09:36:23-07:00","level":"debug","state":"HEALTHY","message":"updating unit state","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"0000-01-01T00:00:00.000Z","message":"","component":{"binary":"","dataset":"elastic_agent.","id":"fake-default","type":"fake"},"log":{"source":"fake-default"},"message":"kill_on_interval config set value","level":"trace","kill_on_interval":false,"time":"2024-03-29T09:36:23-07:00","ecs.version":"1.6.0"}
    manager_fake_input_test.go:408: component state changed: {State:HEALTHY Message:Healthy: communicating with pid '7649' Units:map[{UnitType:input UnitID:fake-input}:{State:HEALTHY Message:Fake Healthy Payload:map[] unitState:2 unitMessage:Fake Healthy unitPayload:map[] configStateIdx:1 err:<nil>}] Features:<nil> FeaturesIdx:1 Component:<nil> ComponentIdx:1 VersionInfo:{Name:fake Meta:map[input:fake] BuildHash:} expectedUnits:map[{UnitType:0 UnitID:fake-input}:{state:2 configStateIdx:1 config:0xc00079a090 err:<nil> logLevel:4}] expectedFeatures:<nil> expectedFeaturesIdx:1 expectedComponent:<nil> expectedComponentIdx:1}
    manager_fake_input_test.go:422: Healthy iteration 0 starting at 2024-03-29 09:36:23.985758 -0700 PDT m=+4.452220815
    manager_fake_input_test.go:408: component state changed: {State:HEALTHY Message:Healthy: communicating with pid '7649' Units:map[{UnitType:input UnitID:fake-input}:{State:HEALTHY Message:Fake Healthy Payload:map[] unitState:2 unitMessage:Fake Healthy unitPayload:map[] configStateIdx:1 err:<nil>}] Features:<nil> FeaturesIdx:1 Component:apm_config:{elastic:{tls:{skip_verify:true server_cert:"servercert" server_ca:"serverca"} environment:"test" api_key:"apiKey" secret_token:"secretToken" hosts:"host1" hosts:"host2" hosts:"host3"}} ComponentIdx:1 VersionInfo:{Name:fake Meta:map[input:fake] BuildHash:} expectedUnits:map[{UnitType:0 UnitID:fake-input}:{state:2 configStateIdx:1 config:0xc00079a090 err:<nil> logLevel:4}] expectedFeatures:<nil> expectedFeaturesIdx:1 expectedComponent:0xc0002c8740 expectedComponentIdx:2}
    manager_fake_input_test.go:422: Healthy iteration 1 starting at 2024-03-29 09:36:23.987066 -0700 PDT m=+4.453529339
{"log.level":"info","@timestamp":"0000-01-01T00:00:00.000Z","message":"","component":{"binary":"","dataset":"elastic_agent.","id":"fake-default","type":"fake"},"log":{"source":"fake-default"},"level":"info","state":"HEALTHY","expectedState":"HEALTHY","time":"2024-03-29T09:36:23-07:00","message":"unit change received","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"0000-01-01T00:00:00.000Z","message":"","component":{"binary":"","dataset":"elastic_agent.","id":"fake-default","type":"fake"},"log":{"source":"fake-default"},"time":"2024-03-29T09:36:23-07:00","message":"kill_on_interval config set value","level":"trace","kill_on_interval":false,"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"0000-01-01T00:00:00.000Z","message":"","component":{"binary":"","dataset":"elastic_agent.","id":"fake-default","type":"fake"},"log":{"source":"fake-default"},"state":"HEALTHY","message":"updating unit state","time":"2024-03-29T09:36:23-07:00","level":"debug","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"0000-01-01T00:00:00.000Z","message":"","component":{"binary":"","dataset":"elastic_agent.","id":"fake-default","type":"fake"},"log":{"source":"fake-default"},"level":"info","apmConfig":{"elastic":{"api_key":"apiKey","environment":"test","hosts":["host1","host2","host3"],"secret_token":"secretToken","tls":{"server_ca":"serverca","server_cert":"servercert","skip_verify":true}}},"time":"2024-03-29T09:36:23-07:00","message":"updating apm configuration","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"0000-01-01T00:00:00.000Z","message":"","component":{"binary":"","dataset":"elastic_agent.","id":"fake-default","type":"fake"},"log":{"source":"fake-default"},"level":"info","time":"2024-03-29T09:36:24-07:00","message":"executing retrieve_apm_config action","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"0000-01-01T00:00:00.000Z","message":"","component":{"binary":"","dataset":"elastic_agent.","id":"fake-default","type":"fake"},"log":{"source":"fake-default"},"level":"debug","time":"2024-03-29T09:36:24-07:00","message":"stored apm config elastic:{tls:{skip_verify:true server_cert:\"servercert\" server_ca:\"serverca\"} environment:\"test\" api_key:\"apiKey\" secret_token:\"secretToken\" hosts:\"host1\" hosts:\"host2\" hosts:\"host3\"}","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"0000-01-01T00:00:00.000Z","message":"","component":{"binary":"","dataset":"elastic_agent.","id":"fake-default","type":"fake"},"log":{"source":"fake-default"},"level":"info","state":"HEALTHY","expectedState":"HEALTHY","time":"2024-03-29T09:36:24-07:00","message":"unit change received","ecs.version":"1.6.0"}
    manager_fake_input_test.go:408: component state changed: {State:HEALTHY Message:Healthy: communicating with pid '7649' Units:map[{UnitType:input UnitID:fake-input}:{State:HEALTHY Message:Fake Healthy Payload:map[] unitState:2 unitMessage:Fake Healthy unitPayload:map[] configStateIdx:1 err:<nil>}] Features:<nil> FeaturesIdx:1 Component:apm_config:{elastic:{tls:{skip_verify:true} environment:"test-modified" api_key:"apiKey" secret_token:"secretToken" hosts:"newhost1" hosts:"host2" hosts:"differenthost3"}} ComponentIdx:1 VersionInfo:{Name:fake Meta:map[input:fake] BuildHash:} expectedUnits:map[{UnitType:0 UnitID:fake-input}:{state:2 configStateIdx:1 config:0xc00079a090 err:<nil> logLevel:4}] expectedFeatures:<nil> expectedFeaturesIdx:1 expectedComponent:0xc0000ad200 expectedComponentIdx:3}
{"log.level":"info","@timestamp":"0000-01-01T00:00:00.000Z","message":"","component":{"binary":"","dataset":"elastic_agent.","id":"fake-default","type":"fake"},"log":{"source":"fake-default"},"level":"trace","kill_on_interval":false,"time":"2024-03-29T09:36:24-07:00","message":"kill_on_interval config set value","ecs.version":"1.6.0"}
    manager_fake_input_test.go:422: Healthy iteration 2 starting at 2024-03-29 09:36:24.041257 -0700 PDT m=+4.507720520
{"log.level":"info","@timestamp":"0000-01-01T00:00:00.000Z","message":"","component":{"binary":"","dataset":"elastic_agent.","id":"fake-default","type":"fake"},"log":{"source":"fake-default"},"level":"debug","state":"HEALTHY","message":"updating unit state","time":"2024-03-29T09:36:24-07:00","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"0000-01-01T00:00:00.000Z","message":"","component":{"binary":"","dataset":"elastic_agent.","id":"fake-default","type":"fake"},"log":{"source":"fake-default"},"apmConfig":{"elastic":{"api_key":"apiKey","environment":"test-modified","hosts":["newhost1","host2","differenthost3"],"secret_token":"secretToken","tls":{"skip_verify":true}}},"time":"2024-03-29T09:36:24-07:00","message":"updating apm configuration","level":"info","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"0000-01-01T00:00:00.000Z","message":"","component":{"binary":"","dataset":"elastic_agent.","id":"fake-default","type":"fake"},"log":{"source":"fake-default"},"level":"info","time":"2024-03-29T09:36:24-07:00","message":"executing retrieve_apm_config action","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"0000-01-01T00:00:00.000Z","message":"","component":{"binary":"","dataset":"elastic_agent.","id":"fake-default","type":"fake"},"log":{"source":"fake-default"},"time":"2024-03-29T09:36:24-07:00","message":"stored apm config elastic:{tls:{skip_verify:true} environment:\"test-modified\" api_key:\"apiKey\" secret_token:\"secretToken\" hosts:\"newhost1\" hosts:\"host2\" hosts:\"differenthost3\"}","level":"debug","ecs.version":"1.6.0"}
    manager_fake_input_test.go:408: component state changed: {State:HEALTHY Message:Healthy: communicating with pid '7649' Units:map[{UnitType:input UnitID:fake-input}:{State:HEALTHY Message:Fake Healthy Payload:map[] unitState:2 unitMessage:Fake Healthy unitPayload:map[] configStateIdx:1 err:<nil>}] Features:<nil> FeaturesIdx:1 Component: ComponentIdx:1 VersionInfo:{Name:fake Meta:map[input:fake] BuildHash:} expectedUnits:map[{UnitType:0 UnitID:fake-input}:{state:2 configStateIdx:1 config:0xc00079a090 err:<nil> logLevel:4}] expectedFeatures:<nil> expectedFeaturesIdx:1 expectedComponent:0xc000588200 expectedComponentIdx:4}
    manager_fake_input_test.go:422: Healthy iteration 3 starting at 2024-03-29 09:36:24.096162 -0700 PDT m=+4.562625291
{"log.level":"info","@timestamp":"0000-01-01T00:00:00.000Z","message":"","component":{"binary":"","dataset":"elastic_agent.","id":"fake-default","type":"fake"},"log":{"source":"fake-default"},"expectedState":"HEALTHY","time":"2024-03-29T09:36:24-07:00","message":"unit change received","level":"info","state":"HEALTHY","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"0000-01-01T00:00:00.000Z","message":"","component":{"binary":"","dataset":"elastic_agent.","id":"fake-default","type":"fake"},"log":{"source":"fake-default"},"kill_on_interval":false,"time":"2024-03-29T09:36:24-07:00","message":"kill_on_interval config set value","level":"trace","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"0000-01-01T00:00:00.000Z","message":"","component":{"binary":"","dataset":"elastic_agent.","id":"fake-default","type":"fake"},"log":{"source":"fake-default"},"level":"debug","state":"HEALTHY","message":"updating unit state","time":"2024-03-29T09:36:24-07:00","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"0000-01-01T00:00:00.000Z","message":"","component":{"binary":"","dataset":"elastic_agent.","id":"fake-default","type":"fake"},"log":{"source":"fake-default"},"level":"info","apmConfig":null,"time":"2024-03-29T09:36:24-07:00","message":"updating apm configuration","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"0000-01-01T00:00:00.000Z","message":"","component":{"binary":"","dataset":"elastic_agent.","id":"fake-default","type":"fake"},"log":{"source":"fake-default"},"level":"info","time":"2024-03-29T09:36:24-07:00","message":"executing retrieve_apm_config action","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"0000-01-01T00:00:00.000Z","message":"","component":{"binary":"","dataset":"elastic_agent.","id":"fake-default","type":"fake"},"log":{"source":"fake-default"},"level":"debug","time":"2024-03-29T09:36:24-07:00","message":"stored apm config <nil>","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2024-03-29T09:36:24.149-0700","log.origin":{"file.name":"runtime/manager.go","file.line":779},"message":"Stopping component \"fake-default\"","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2024-03-29T09:36:24.351-0700","log.origin":{"file.name":"runtime/manager.go","file.line":835},"message":"component \"fake-default\" stopped.","ecs.version":"1.6.0"}
```

**Comment by rdner** [comment]
Another failure https://buildkite.com/elastic/elastic-agent/builds/8629#018f38e0-b88f-4c04-9e34-6cd6d9844928

**Comment by pkoutsovasilis** [comment]
another occurrence of this [here](https://buildkite.com/elastic/elastic-agent/builds/18290#01956e03-54e3-49f3-af46-2ccd046c0abd/817-1128)
