### ISSUE TITLE
panic while uninstalling part of Elastic Agent

### ISSUE THREAD

**Issue by ph** [elastic/elastic-agent#806]
```
panic: sync: negative WaitGroup counter
goroutine 55 [running]:
sync.(*WaitGroup).Add(0xc0002fa930?, 0xc0000ddd40?)
sync/waitgroup.go:80 +0xda\rsync.(*WaitGroup).Done(...)
sync/waitgroup.go:105
[github.com/elastic/elastic-agent/internal/pkg/agent/install.applyDynamics.func1](https://github.com/elastic/elastic-agent/internal/pkg/agent/install.applyDynamics.func1)({0xc0009494d0?, 0xc000524bb0?, 0x6?})
[github.com/elastic/elastic-agent/internal/pkg/agent/install/uninstall.go:240](https://github.com/elastic/elastic-agent/internal/pkg/agent/install/uninstall.go:240) +0x4c
[github.com/elastic/elastic-agent/internal/pkg/composable.(*controller).Run.func1()](https://github.com/elastic/elastic-agent/internal/pkg/composable.(*controller).Run.func1())
[github.com/elastic/elastic-agent/internal/pkg/composable/controller.go:175](https://github.com/elastic/elastic-agent/internal/pkg/composable/controller.go:175) +0x1df
created by [github.com/elastic/elastic-agent/internal/pkg/composable.(*controller).Run](https://github.com/elastic/elastic-agent/internal/pkg/composable.(*controller).Run)
[github.com/elastic/elastic-agent/internal/pkg/composable/controller.go:128](https://github.com/elastic/elastic-agent/internal/pkg/composable/controller.go:128) +0x71b"

```

./elastic-agent install -v -n --url=[xxxx.fleet.us-east-1.aws.found.io:443](https://xxxx.fleet.us-east-1.aws.found.io/) --enrollment-token=xxxxxxxx

**Comment by ph** [comment]
This is because the `composable` system that take care of the different provider will continuously run and call the callback and we are only interested in the first run to collect the variables. I will make a PR that will stop the `composable` after the first execution of the callback.
