### ISSUE TITLE
Fleet-server panics in 8.3.2

### ISSUE THREAD

**Issue by adriansr** [elastic/elastic-agent#831]
Please post all questions and issues concerning the Elastic Agent on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: 8.3.2
- Operating System: Docker
- Discuss Forum URL:
- Steps to Reproduce:

After bringing up the testing stack with elastic-package I observed this in the logs:

```
fleet-server_1               | {"log.level":"error","@timestamp":"2022-08-02T08:28:58.942Z","log.origin":{"file.name":"process/stdlogger.go","file.line":54},"message":"filebeat_monitoring stderr: \"panic: close of closed channel\\n\\ngoroutine 55 [running]:\\ngithub.com/elastic/beats/v7/filebeat/beater.(*Filebeat).Stop(0xc0005fbc50)\\n\\t/go/src/github.com/elastic/beats/filebeat/beater/filebeat.go:428 +0x3f\\ngithub.com/elastic/beats/v7/libbeat/cmd/instance.(*Beat).launch.func5()\\n\\t/go/src/github.com/elastic/beats/libbeat/cmd/instance/beat.go:461 +0x55\\nsync.(*Once).doSlow(0x0?, 0x0?)\\n\\t/usr/local/go/src/sync/once.go:68 +0xc2\\n\"","agent.console.name":"filebeat_monitoring","agent.console.type":"stderr","ecs.version":"1.6.0"}
fleet-server_1               | {"log.level":"error","@timestamp":"2022-08-02T08:28:58.943Z","log.origin":{"file.name":"process/stdlogger.go","file.line":54},"message":"filebeat_monitoring stderr: \"sync.(*Once).Do(...)\\n\\t/usr/local/go/src/sync/once.go:59\\ngithub.com/elastic/elastic-agent-libs/service.HandleSignals.func1()\\n\\t/go/pkg/mod/github.com/elastic/elastic-agent-libs@v0.2.4/service/service.go:60 +0x19c\\ncreated by github.com/elastic/elastic-agent-libs/service.HandleSignals\\n\\t/go/pkg/mod/github.com/elastic/elastic-agent-libs@v0.2.4/service/service.go:49 +0x18f\\n\"","agent.console.name":"filebeat_monitoring","agent.console.type":"stderr","ecs.version":"1.6.0"}
```

**Comment by adriansr** [comment]
On closer look the panic is happening in the monitoring Beats (Filebeat, Metricbeat). Will open this in the beats repo

**Comment by adriansr** [comment]
Created in https://github.com/elastic/beats/issues/32608
